import test from 'node:test';
import assert from 'node:assert/strict';
import {createGroqLLM} from '../api/_voice/providers/groq.js';
import {createVoiceProviders,supportedVoiceProviders,voiceProviderStatus} from '../api/_voice/providers/index.js';
import {createControlledTestHandler,preflightSelectedVoiceProviders} from '../api/ai-controlled-test-call.js';

function sse(parts){const enc=new TextEncoder();let i=0;return new ReadableStream({pull(controller){if(i>=parts.length)return controller.close();controller.enqueue(enc.encode(parts[i++]));}})}
function groqStream(...deltas){return sse([...deltas.map(delta=>`data: ${JSON.stringify({choices:[{delta:{content:delta}}]})}\n\n`),'data: [DONE]\n\n'])}
function collect(llm,args={}){return (async()=>{const out=[];for await(const item of llm.streamResponse({system:'rules',history:[],user:'hello',signal:new AbortController().signal,...args}))out.push(item);return out})()}
function rateResponse(retry='0.01'){return new Response(JSON.stringify({error:{message:'rate limit'}}),{status:429,headers:{'retry-after':retry,'x-ratelimit-limit-tokens':'8000','x-ratelimit-remaining-tokens':'0','x-ratelimit-reset-tokens':'1s'}})}

function preflightAdmin(campaign,configs=[]){return {from(table){if(table==='ai_call_campaigns')return {select(){return {eq(){return {single:async()=>({data:campaign,error:null})}}}}};if(table==='ai_provider_configs')return {select(){return {eq:async()=>({data:configs,error:null})}}};throw new Error(`unexpected table ${table}`)}}}
function response(){return {statusCode:200,body:null,headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.statusCode=n;return this},json(v){this.body=v;return this}}}
function request(body={}){return {method:'POST',body,headers:{authorization:'Bearer test'}}}
const readyTwilio={status:()=>({configured:true,readyForTest:true,fromNumber:'+15005550006'}),createCall:async()=>{throw new Error('Twilio must not be called in preflight tests')}};
const campaign={id:'11111111-1111-4111-8111-111111111111',stt_provider_slug:'deepgram',llm_provider_slug:'groq',tts_provider_slug:'deepgram'};
const enabledConfigs=[{provider_kind:'stt',provider_slug:'deepgram',enabled:true},{provider_kind:'llm',provider_slug:'groq',enabled:true},{provider_kind:'tts',provider_slug:'deepgram',enabled:true}];

test('Groq realtime default is production GPT-OSS 20B with phone-sized output budget',async()=>{let clock=100;let body=null;const fetchImpl=async(_url,opts)=>{body=JSON.parse(opts.body);return new Response(groqStream('Hi',' there'),{status:200})};const llm=createGroqLLM({apiKey:'configured',fetchImpl,now:()=>++clock});const out=await collect(llm);assert.equal(out.map(x=>x.delta).join(''),'Hi there');assert.ok(Number.isFinite(out[0].firstTokenLatencyMs));assert.equal(body.model,'openai/gpt-oss-20b');assert.equal(body.max_completion_tokens,72);assert.equal(body.reasoning_effort,'low')});
test('120B remains explicitly configurable through realtime_model',async()=>{let body;const llm=createGroqLLM({apiKey:'configured',settings:{realtime_model:'openai/gpt-oss-120b'},fetchImpl:async(_u,o)=>{body=JSON.parse(o.body);return new Response(groqStream('ok'),{status:200})}});await collect(llm);assert.equal(body.model,'openai/gpt-oss-120b');assert.equal(llm.status().model,'openai/gpt-oss-120b')});
test('Groq performs only one bounded retry when retry-after is tiny',async()=>{let calls=0;const llm=createGroqLLM({apiKey:'configured',settings:{max_rate_limit_retry_ms:100},fetchImpl:async()=>{calls++;return calls===1?rateResponse('0.01'):new Response(groqStream('Recovered.'),{status:200})}});const out=await collect(llm);assert.equal(calls,2);assert.equal(out.map(x=>x.delta).join(''),'Recovered.');assert.equal(out[0].rateLimitRetry.retried,true);assert.equal(out[0].rateLimitRetry.retryAfterMs,10)});
test('Groq does not silently wait on a long retry-after',async()=>{let calls=0;const llm=createGroqLLM({apiKey:'configured',settings:{max_rate_limit_retry_ms:100},fetchImpl:async()=>{calls++;return rateResponse('2')}});await assert.rejects(collect(llm),e=>e.code==='LLM_RATE_LIMIT'&&e.retryAfterMs===2000);assert.equal(calls,1)});
test('second 429 after bounded retry is surfaced without an infinite loop',async()=>{let calls=0;const llm=createGroqLLM({apiKey:'configured',settings:{max_rate_limit_retry_ms:100},fetchImpl:async()=>{calls++;return rateResponse('0.01')}});await assert.rejects(collect(llm),e=>e.code==='LLM_RATE_LIMIT');assert.equal(calls,2)});
test('Groq request abort cancels an in-flight generation',async()=>{const fetchImpl=async(_url,{signal})=>new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error(String(signal.reason||'aborted')),{name:'AbortError'})),{once:true}));const llm=createGroqLLM({apiKey:'configured',fetchImpl,settings:{connect_timeout_ms:5000,timeout_ms:5000}});const controller=new AbortController();const run=(async()=>{for await(const _ of llm.streamResponse({system:'rules',history:[],user:'hello',signal:controller.signal})){} })();setTimeout(()=>controller.abort('barge in'),20);await assert.rejects(run,e=>e.name==='AbortError')});
test('Groq timeout is bounded and normalized',async()=>{const fetchImpl=async(_url,{signal})=>new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error(String(signal.reason||'timeout')),{name:'AbortError'})),{once:true}));const llm=createGroqLLM({apiKey:'configured',fetchImpl,settings:{connect_timeout_ms:5000,timeout_ms:100}});await assert.rejects(collect(llm),e=>e.code==='LLM_TIMEOUT')});
test('Groq authentication failure is normalized',async()=>{const llm=createGroqLLM({apiKey:'configured',fetchImpl:async()=>new Response(JSON.stringify({error:{message:'invalid api key'}}),{status:401})});await assert.rejects(collect(llm),e=>e.code==='LLM_AUTH'&&e.status===401)});
test('Groq provider errors are sanitized before surfacing',async()=>{const secret='gsk_super_secret_key_123456';const llm=createGroqLLM({apiKey:'configured',fetchImpl:async()=>new Response(JSON.stringify({error:{message:`Authorization Bearer ${secret} failed`}}),{status:400})});await assert.rejects(collect(llm),e=>e.code==='LLM_PROVIDER'&&!e.message.includes(secret)&&e.message.includes('[REDACTED]'))});
test('Groq compliance validator allows a valid response',async()=>{const fetchImpl=async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({allowed:true,violations:[],unsupported_claims:[]})}}]}),{status:200});const llm=createGroqLLM({apiKey:'configured',fetchImpl});const verdict=await llm.validate({candidate:'May I ask how you get new clients?',hardRules:[],knowledge:[],signal:new AbortController().signal});assert.equal(verdict.allowed,true)});
test('Groq malformed compliance output fails closed',async()=>{const fetchImpl=async()=>new Response(JSON.stringify({choices:[{message:{content:'not-json'}}]}),{status:200});const llm=createGroqLLM({apiKey:'configured',fetchImpl});const verdict=await llm.validate({candidate:'claim',hardRules:[],knowledge:[],signal:new AbortController().signal});assert.equal(verdict.allowed,false);assert.deepEqual(verdict.violations,['validator_parse_failure'])});
test('voice provider factory selects Groq and still supports OpenAI',()=>{assert.deepEqual(supportedVoiceProviders.llm,['openai','groq']);const rows=[{provider_kind:'llm',provider_slug:'groq',enabled:true,settings:{realtime_model:'openai/gpt-oss-120b'}},{provider_kind:'llm',provider_slug:'openai',enabled:true,settings:{model:'openai-test'}}];const providers=createVoiceProviders({providerConfigs:rows,env:{GROQ_API_KEY:'groq-key',OPENAI_API_KEY:'openai-key'}});assert.equal(providers.llm('groq').status().model,'openai/gpt-oss-120b');assert.equal(providers.llm('openai').status().model,'openai-test')});
test('voice provider status reports Groq independently of OpenAI',()=>{const status=voiceProviderStatus({GROQ_API_KEY:'groq',DEEPGRAM_API_KEY:'dg'});assert.equal(status.groq.configured,true);assert.equal(status.openai.configured,false)});
test('Groq selected-provider preflight succeeds without OPENAI_API_KEY',async()=>{const result=await preflightSelectedVoiceProviders(preflightAdmin(campaign,enabledConfigs),campaign.id,{deepgram:{configured:true},groq:{configured:true},openai:{configured:false}});assert.equal(result.ok,true);assert.equal(result.selected.llm,'groq')});
test('controlled call cannot reach Twilio when selected Groq is unconfigured',async()=>{let calls=0;const provider={...readyTwilio,createCall:async()=>{calls++}};const admin=preflightAdmin(campaign,enabledConfigs);const handler=createControlledTestHandler({providerFactory:()=>provider,requireAdminFn:async()=>({admin,user:{id:'admin'}}),liveEnabledFn:()=>true,voiceStatusFn:()=>({deepgram:{configured:true},groq:{configured:false},openai:{configured:true}})});const r=response();await handler(request({action:'place',confirmation:'PLACE ONE REAL TWILIO CALL',campaignId:campaign.id,destination:'+12295373671',requestKey:'phase7_groq_preflight_0001'}),r);assert.equal(r.statusCode,503);assert.equal(calls,0)});
