import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {buildTurnContext,groupInstructions} from '../api/_voice/context.js';
import {createTwilioMediaTransport} from '../api/_voice/media/twilio.js';
import {createDeepgramTTS} from '../api/_voice/providers/deepgram.js';
import {VoiceOrchestrator} from '../api/_voice/orchestrator.js';

function representativeContext(){const knowledge=Array.from({length:18},(_,i)=>({id:`k${i}`,category:i===0?'pricing':i===1?'service':'case_notes',title:`Knowledge ${i}`,content:`Verified company fact ${i}. `.repeat(18),tags:i<2?['realtor','lead generation']:[]}));const regulations=Array.from({length:8},(_,i)=>({enforcement_level:i<4?'hard':'advisory',priority:100-i,title:`Rule ${i}`,rule_text:`Do not make unsupported claim ${i}. `.repeat(8)}));const instructions=groupInstructions(Array.from({length:16},(_,i)=>({instruction_type:['objective','audience','personality','opening','discovery','qualification','objection','closing'][i%8],title:`Guide ${i}`,content:`Campaign guidance ${i}. `.repeat(12),priority:100-i,enabled:true})));return {campaign:{compliance_settings:{}},knowledge,regulations,instructions,prospect:{first_name:'John',company:'Example Realty',city:'Austin',notes:'Long CRM note '.repeat(80)},callbacks:[]}}

test('representative six-turn realtime request stays compact and recent-history bounded',()=>{const ctx=representativeContext();const history=[];for(let i=0;i<12;i++)history.push({role:i%2?'assistant':'user',content:`Turn ${i} `+'conversation '.repeat(45)});const state={call_stage:'discovery',objection_type:'soft_brush_off',brush_off_count:1,prospect_interest:'low',prior_questions_asked:['How are you getting business?'],prior_objections:[{type:'soft_brush_off',text:'I am good'}]};const req=buildTurnContext(ctx,{prospectText:'We mostly use referrals but what does it cost?',strategy:'verified_price_only',state,directive:'One sentence. Ask at most one question.',history});const legacy=JSON.stringify({knowledge:ctx.knowledge,regulations:ctx.regulations,instructions:ctx.instructions,prospect:ctx.prospect,history});const legacyEstimate=Math.ceil(legacy.length/3.7);console.log('PHASE7_CONTEXT_BENCHMARK',JSON.stringify({legacy_estimated_tokens:legacyEstimate,compact_estimated_tokens:req.estimatedInputTokens,compact_chars:req.inputChars,history_messages:req.history.length,relevant_knowledge:req.knowledge.length}));assert.ok(req.estimatedInputTokens<1400);assert.ok(legacyEstimate>req.estimatedInputTokens*3);assert.equal(req.history.length,6);assert.ok(req.knowledge.length<=3)});
test('history truncation keeps the newest relevant turns',()=>{const ctx=representativeContext();const history=Array.from({length:14},(_,i)=>({role:i%2?'assistant':'user',content:`message-${i}`}));const req=buildTurnContext(ctx,{prospectText:'hello',strategy:'discovery_follow_up',state:{},history});assert.deepEqual(req.history.map(x=>x.content),Array.from({length:6},(_,i)=>`message-${i+8}`))});
test('static context is not duplicated inside each history item',()=>{const ctx=representativeContext();const history=[{role:'user',content:'referrals'},{role:'assistant',content:'Gotcha.'}];const req=buildTurnContext(ctx,{prospectText:'How much?',strategy:'verified_price_only',state:{},history});assert.equal(req.history.some(x=>x.content.includes('HARD/REQUIRED COMPANY REGULATIONS')),false);assert.equal((req.user.match(/RELEVANT VERIFIED KNOWLEDGE/g)||[]).length,1)});

class Socket{constructor(){this.readyState=1;this.sent=[]}send(x){this.sent.push(JSON.parse(String(x)))}}
function media(seq,byte){return {event:'media',sequenceNumber:String(seq),media:{payload:Buffer.alloc(160,byte).toString('base64'),timestamp:String(seq*20)}}}
test('one sustained speech burst creates one start and one end, then a later burst creates the second',()=>{let now=1000;const t=createTwilioMediaTransport({socket:new Socket(),now:()=>now,bargeInRms:0.045,bargeInFrames:4,speechEndFrames:4});t.start({streamSid:'MZ1',start:{callSid:'CA1'}});let starts=0,ends=0;for(let i=1;i<=8;i++){now+=20;const m=t.ingest(media(i,0x00));if(m.speechStarted)starts++;if(m.speechEnded)ends++}for(let i=9;i<=12;i++){now+=20;const m=t.ingest(media(i,0xff));if(m.speechStarted)starts++;if(m.speechEnded)ends++}assert.equal(starts,1);assert.equal(ends,1);for(let i=13;i<=16;i++){now+=20;if(t.ingest(media(i,0x00)).speechStarted)starts++}assert.equal(starts,2)});
test('background silence/noise never becomes a barge-in burst',()=>{const t=createTwilioMediaTransport({socket:new Socket(),bargeInRms:0.045,bargeInFrames:4});t.start({streamSid:'MZ1',start:{callSid:'CA1'}});let starts=0;for(let i=1;i<=30;i++)if(t.ingest(media(i,0xfe)).speechStarted)starts++;assert.equal(starts,0)});
test('duplicate media sequence cannot create a duplicate speech start',()=>{const t=createTwilioMediaTransport({socket:new Socket(),bargeInRms:0.045,bargeInFrames:4});t.start({streamSid:'MZ1',start:{callSid:'CA1'}});for(let i=1;i<=4;i++)t.ingest(media(i,0x00));assert.equal(t.ingest(media(4,0x00)).duplicate,true);assert.equal(t.state.inSpeechBurst,true)});

function voiceHarness({streamError=null,responseText='One short sentence.'}={}){const rpc=[],events=[],updates=[],spoken=[],marks=[];let transportClears=0,ttsClears=0,flushes=0;const admin={rpc:async(name,args)=>{rpc.push({name,args});return {data:{sequence_no:rpc.length},error:null}},from:table=>({insert:async row=>{events.push({table,row});return {error:null}},update:row=>({eq:async()=>{updates.push({table,row});return {error:null}}})})};const stt={slug:'stt-test',status:()=>({model:'nova-3'}),async connect(){},sendAudio(){},close(){}};const llm={slug:'groq',status:()=>({model:'openai/gpt-oss-20b'}),async *streamResponse(){if(streamError)throw streamError;yield {delta:responseText,firstTokenLatencyMs:20}},async validate(){return {allowed:true,violations:[],unsupportedClaims:[]}}};const tts={slug:'deepgram',status:()=>({voice:'aura-2-apollo-en',speed:1.12}),async connect(){},speak:x=>spoken.push(x),flush(){flushes++},clear(){ttsClears++},close(){}};const pending=new Map();const transport={clear(){transportClears++;pending.clear();return true},sendAudio(){return true},mark(turnId,metadata={}){const name=`m${marks.length+1}`;const mark={name,turnId,metadata,sentAt:0};marks.push(mark);pending.set(name,mark);return name},acknowledgeMark(evt){const m=pending.get(evt.mark?.name);if(m)pending.delete(evt.mark.name);return m||null},close(){},ingest(){return {ignored:true}}};const context={campaign:{compliance_settings:{}},regulations:[],knowledge:[],instructions:groupInstructions([]),prospect:{},callbacks:[]};const session={id:'s',attempt_id:'a',prospect_record_id:'p',stt_provider_slug:'stt-test',llm_provider_slug:'groq',tts_provider_slug:'deepgram',turn_no:0,interruption_count:0,latency_metrics:{},provider_errors:[],provider_states:{}};const voice=new VoiceOrchestrator({admin,session,context,providers:{stt:()=>stt,llm:()=>llm,tts:()=>tts},transport,now:(()=>{let n=1000;return()=>++n})()});return {voice,rpc,events,updates,spoken,marks,get transportClears(){return transportClears},get ttsClears(){return ttsClears},get flushes(){return flushes}}}

test('interrupted approved sentence never becomes final spoken transcript or assistant history',async()=>{const h=voiceHarness();await h.voice.generateAgentTurn('hello');h.voice.onTtsAudio(Buffer.alloc(3200));assert.equal(h.voice.history.length,0);h.voice.interrupt('audio_vad',1000);await new Promise(r=>setTimeout(r,5));assert.equal(h.voice.history.some(x=>x.role==='assistant'),false);assert.equal(h.rpc.some(x=>x.args?.p_speaker==='agent'),false);const event=h.events.find(x=>x.row?.event_type==='voice.agent.interrupted_delivery');assert.ok(event);assert.equal(event.row.payload.approved_text,'One short sentence.');assert.equal(event.row.payload.interrupted_before_completion,true)});
test('only final Twilio playback acknowledgement promotes approved text into spoken history',async()=>{const h=voiceHarness();await h.voice.generateAgentTurn('hello');h.voice.onTtsAudio(Buffer.alloc(3200));h.voice.onTtsFlushed();const final=h.marks.find(x=>x.metadata.kind==='final');assert.ok(final);await h.voice.onMark({mark:{name:final.name}});assert.equal(h.voice.history.at(-1).content,'One short sentence.');assert.equal(h.rpc.filter(x=>x.args?.p_speaker==='agent').length,1)});
test('old progress playback mark after interruption cannot resurrect stale turn',async()=>{const h=voiceHarness();await h.voice.generateAgentTurn('hello');h.voice.onTtsAudio(Buffer.alloc(3200));const progress=h.marks.find(x=>x.metadata.kind==='progress');h.voice.interrupt('audio_vad',1000);await h.voice.onMark({mark:{name:progress.name}});assert.equal(h.voice.current,null);assert.equal(h.voice.history.some(x=>x.role==='assistant'),false)});
test('Groq rate limit uses validated fallback instead of failing the whole session',async()=>{const e=Object.assign(new Error('rate'),{code:'LLM_RATE_LIMIT',status:429,retryAfterMs:900,rateLimit:{limitTokens:8000,remainingTokens:0}});const h=voiceHarness({streamError:e});await h.voice.generateAgentTurn('hello',{decision:{strategy:'discovery_follow_up',state:{}}});assert.equal(h.voice.closed,false);assert.equal(h.voice.session.status,'speaking');assert.equal(h.voice.current.strategy,'rate_limit_fallback');assert.ok(h.events.some(x=>x.row?.event_type==='voice.llm.rate_limited'))});
test('interrupt clear path is synchronous and cannot count one active turn twice',async()=>{const h=voiceHarness();await h.voice.generateAgentTurn('hello');const first=h.voice.interrupt('audio_vad',1000);const second=h.voice.interrupt('stt_speech_started',1001);assert.equal(first,true);assert.equal(second,false);assert.equal(h.voice.session.interruption_count,1);assert.equal(h.transportClears,1);assert.equal(h.ttsClears,1)});
test('two approved sentences share one TTS flush instead of artificial per-sentence flush gaps',async()=>{const h=voiceHarness({responseText:'First short sentence. Second short sentence.'});await h.voice.generateAgentTurn('hello');assert.equal(h.spoken.length,2);assert.equal(h.flushes,1)});

class MockWs extends EventEmitter{static OPEN=1;static instances=[];constructor(url){super();this.url=url;this.readyState=0;MockWs.instances.push(this)}send(){}close(){this.readyState=3;this.emit('close',1000,'closed')}terminate(){this.close()}open(){this.readyState=1;this.emit('open')}}
test('Apollo speed defaults to 1.12 and configured speed propagates to Deepgram websocket',async()=>{MockWs.instances=[];const a=createDeepgramTTS({apiKey:'x',WebSocketImpl:MockWs});const p=a.connect();MockWs.instances[0].open();await p;assert.equal(a.status().voice,'aura-2-apollo-en');assert.equal(a.status().speed,1.12);assert.match(MockWs.instances[0].url,/speed=1.12/);a.close();MockWs.instances=[];const b=createDeepgramTTS({apiKey:'x',WebSocketImpl:MockWs,settings:{speed:1.2}});const q=b.connect();MockWs.instances[0].open();await q;assert.match(MockWs.instances[0].url,/speed=1.2/);b.close()});
