import crypto from 'node:crypto';
import {buildSystemPrompt,hardRules} from './context.js';
import {DEFAULT_QUALITY_SETTINGS,initialConversationState,decideConversation,recordAgentTurn,buildOpeningDirective,buildTurnDirective,evaluateHumanness} from './conversation.js';

function compactError(e){return {code:String(e?.code||'VOICE_ERROR').slice(0,80),message:String(e?.message||'Voice provider failure.').slice(0,500),at:new Date().toISOString()}}
function splitSpeakable(text,final=false){const chunks=[];let rest=text;const re=/^([\s\S]*?[.!?](?:\s+|$))/;while(true){const m=rest.match(re);if(!m)break;const c=m[1].trim();if(c)chunks.push(c);rest=rest.slice(m[1].length)}if(final&&rest.trim())return {chunks:[...chunks,rest.trim()],rest:''};return {chunks,rest}}
function historyTrim(h,max=24){return h.slice(Math.max(0,h.length-max))}
function average(values){const xs=values.filter(Number.isFinite);return xs.length?Math.round(xs.reduce((a,b)=>a+b,0)/xs.length):null}
function qualitySettings(context){const q=context?.campaign?.compliance_settings?.voice_quality||{};return {...DEFAULT_QUALITY_SETTINGS,...q,max_spoken_sentences:Math.max(1,Math.min(3,Number(q.max_spoken_sentences||DEFAULT_QUALITY_SETTINGS.max_spoken_sentences))),max_words:Math.max(15,Math.min(60,Number(q.max_words||DEFAULT_QUALITY_SETTINGS.max_words))),brush_off_limit:Math.max(1,Math.min(3,Number(q.brush_off_limit||DEFAULT_QUALITY_SETTINGS.brush_off_limit)))}}

export class VoiceOrchestrator{
 constructor({admin,session,context,providers,transport,socket,now=()=>Date.now(),maxSessionMs=30*60*1000,maxTurns=100}={}){
  this.admin=admin;this.session=session;this.context=context;this.providers=providers;this.transport=transport;this.socket=socket;this.now=now;this.maxSessionMs=maxSessionMs;this.maxTurns=maxTurns;this.startedAt=now();this.turnNo=session.turn_no||0;this.history=[];this.pendingFinal='';this.pendingFinalStart=null;this.pendingFinalEnd=null;this.pendingSpeechEndAt=null;this.pendingConfidence=[];this.pendingSttLatency=[];this.recentFinalSignatures=[];this.current=null;this.generationEpoch=0;this.closed=false;this.patchTimer=null;this.sessionPatch={};this.system=buildSystemPrompt(context);this.hard=hardRules(context);this.quality=qualitySettings(context);this.conversationState=initialConversationState(session?.objection_state?.conversation_state||{});this.connectedAtMs=null;
  this.stt=providers.stt(session.stt_provider_slug);this.llm=providers.llm(session.llm_provider_slug);this.tts=providers.tts(session.tts_provider_slug);
 }
 async patch(patch,immediate=false){Object.assign(this.session,patch);Object.assign(this.sessionPatch,patch,{last_activity_at:new Date().toISOString()});if(immediate)return this.flushPatch();if(!this.patchTimer)this.patchTimer=setTimeout(()=>this.flushPatch().catch(()=>{}),150)}
 async flushPatch(){clearTimeout(this.patchTimer);this.patchTimer=null;const patch=this.sessionPatch;this.sessionPatch={};if(!Object.keys(patch).length)return;await this.admin.from('ai_voice_sessions').update(patch).eq('id',this.session.id)}
 async event(type,payload={}){await this.admin.from('ai_call_events').insert({attempt_id:this.session.attempt_id,event_type:type,event_source:'voice_worker',payload})}
 async transcript(speaker,text,{startMs=0,endMs=null,confidence=null,providerSlug=null,providerSegmentId=null,metadata={}}={}){if(!String(text||'').trim())return null;const {data,error}=await this.admin.rpc('ai_append_transcript_segment',{p_attempt_id:this.session.attempt_id,p_speaker:speaker,p_start_ms:Math.max(0,startMs|0),p_end_ms:endMs==null?null:Math.max(0,endMs|0),p_text:String(text),p_confidence:confidence,p_provider_slug:providerSlug,p_provider_segment_id:providerSegmentId,p_metadata:metadata});if(error)throw error;return data}
 async persistConversationState(immediate=false){await this.patch({objection_state:{...(this.session.objection_state||{}),conversation_state:this.conversationState}},immediate)}
 async start(){
  if(this.closed)throw new Error('session closed');
  await this.patch({status:'connecting',provider_states:{stt:'connecting',llm:'ready',tts:'connecting'}},true);
  await Promise.all([
   this.stt.connect({onState:s=>this.patch({provider_states:{...(this.session.provider_states||{}),stt:s}}),onSpeechStarted:e=>this.onSpeechStarted(e),onInterim:e=>this.onInterim(e),onFinal:e=>this.onFinal(e),onUtteranceEnd:e=>this.onUtteranceEnd(e),onError:e=>this.providerFailure('stt',e),onClose:e=>{if(!this.closed)this.providerFailure('stt',Object.assign(new Error('STT disconnected'),{code:'STT_DISCONNECT',detail:e}))}}),
   this.tts.connect({onState:s=>this.patch({provider_states:{...(this.session.provider_states||{}),tts:s},tts_state:s==='clearing'?'clearing':this.current?.ttsStarted?'speaking':'idle'}),onAudio:b=>this.onTtsAudio(b),onFirstAudio:m=>this.onFirstAudio(m),onFlushed:()=>this.onTtsFlushed(),onError:e=>this.providerFailure('tts',e),onClose:e=>{if(!this.closed)this.providerFailure('tts',Object.assign(new Error('TTS disconnected'),{code:'TTS_DISCONNECT',detail:e}))}})
  ]);
  this.connectedAtMs=this.now();await this.patch({status:'listening',connected_at:new Date().toISOString(),provider_states:{stt:'connected',llm:'ready',tts:'connected'},objection_state:{...(this.session.objection_state||{}),conversation_state:this.conversationState}},true);await this.event('voice.session.connected',{sessionId:this.session.id,providers:{stt:this.session.stt_provider_slug,llm:this.session.llm_provider_slug,tts:this.session.tts_provider_slug},quality:this.quality});
  this.sessionTimeout=setTimeout(()=>this.fail('session',Object.assign(new Error('Maximum controlled voice session duration reached.'),{code:'SESSION_TIMEOUT'})),this.maxSessionMs);
  const openingDecision={state:this.conversationState,strategy:'opening',terminate:false,repeatedStrategy:false};
  await this.generateAgentTurn('The phone call has just connected. Give the opening greeting now. Do not claim the prospect said anything yet.',{opening:true,decision:openingDecision,directive:buildOpeningDirective(this.conversationState,this.context.prospect),userFinalAt:this.connectedAtMs});
 }
 onMedia(evt){if(this.closed)return;const m=this.transport.ingest(evt);if(m.duplicate||m.ignored)return;if(m.speechDetected&&this.current?.ttsStarted)this.interrupt('audio_vad',m.detectedAtMs||this.now());if(m.audio)this.stt.sendAudio(m.audio);if(this.now()-this.startedAt>this.maxSessionMs)this.fail('session',Object.assign(new Error('Session timeout.'),{code:'SESSION_TIMEOUT'}))}
 async onSpeechStarted(e={}){if(this.current?.ttsStarted)await this.interrupt('stt_speech_started',e.atMs||this.now())}
 async onInterim(e){if(this.closed)return;await this.patch({interim_transcript:e.text,status:this.current?.ttsStarted?'interrupted':'listening'});if(this.current?.ttsStarted)await this.interrupt('stt_interim',e.receivedAtMs||this.now())}
 async onFinal(e){if(this.closed)return;this.pendingFinal=[this.pendingFinal,e.text].filter(Boolean).join(' ').trim();this.pendingFinalStart=this.pendingFinalStart??e.startMs;this.pendingFinalEnd=e.endMs;this.pendingSpeechEndAt=Math.max(this.pendingSpeechEndAt||0,Number(e.speechEndAtMs||0))||this.pendingSpeechEndAt;this.pendingConfidence.push(e.confidence);if(Number.isFinite(e.receivedAtMs)&&Number.isFinite(e.speechEndAtMs)&&e.speechEndAtMs>0)this.pendingSttLatency.push(Math.max(0,e.receivedAtMs-e.speechEndAtMs));await this.patch({interim_transcript:e.speechFinal?'':this.pendingFinal});if(e.speechFinal)await this.commitProspectTurn(e.providerSegmentId)}
 async onUtteranceEnd(e={}){if(this.pendingFinal.trim())await this.commitProspectTurn(null,e.atMs||this.now())}
 async commitProspectTurn(providerSegmentId,fallbackSpeechEndAt=null){const text=this.pendingFinal.trim();if(!text)return;const startMs=this.pendingFinalStart??Math.max(0,this.now()-this.startedAt);const endMs=this.pendingFinalEnd??Math.max(startMs,this.now()-this.startedAt);const speechEndAt=this.pendingSpeechEndAt||fallbackSpeechEndAt||this.now();const vals=this.pendingConfidence.filter(Number.isFinite);const confidence=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null;const sttFinalMs=average(this.pendingSttLatency);const signature=`${startMs}:${endMs}:${text}`;this.pendingFinal='';this.pendingFinalStart=null;this.pendingFinalEnd=null;this.pendingSpeechEndAt=null;this.pendingConfidence=[];this.pendingSttLatency=[];
  if(this.recentFinalSignatures.includes(signature)){await this.patch({interim_transcript:''});return}this.recentFinalSignatures.push(signature);if(this.recentFinalSignatures.length>50)this.recentFinalSignatures.shift();
  if(this.current)await this.interrupt('new_final_turn',this.now());
  const last=this.history[this.history.length-1];if(last?.role==='user'&&last.content===text)return;
  await this.transcript('prospect',text,{startMs,endMs,confidence,providerSlug:this.stt.slug,providerSegmentId,metadata:{phase:7,stt_final_latency_ms:sttFinalMs}});this.history.push({role:'user',content:text});this.history=historyTrim(this.history);
  const decision=decideConversation(this.conversationState,text,this.quality);this.conversationState=decision.state;await this.persistConversationState(false);await this.patch({interim_transcript:'',last_prospect_utterance:text,status:'thinking'});
  if(decision.classification.type==='explicit_do_not_call')await this.persistDnc(text);
  const directive=buildTurnDirective(decision,this.quality);await this.event('voice.conversation.strategy',{type:decision.classification.type,strategy:decision.strategy,brushOffCount:this.conversationState.brush_off_count,terminate:decision.terminate});
  await this.generateAgentTurn(text,{userAlreadyInHistory:true,userFinalAt:speechEndAt,sttFinalMs,decision,directive,endAfterPlayback:decision.terminate,terminationReason:decision.terminationReason})
 }
 async persistDnc(text){try{const {error}=await this.admin.from('ai_suppressions').insert({prospect_record_id:this.session.prospect_record_id,phone_e164:this.context.attempt?.phone_e164||null,campaign_id:null,scope:'global',suppression_type:'do_not_call',reason:String(text||'Explicit do-not-call request').slice(0,500),source_attempt_id:this.session.attempt_id,active:true});if(error)throw error;await this.admin.from('ai_call_attempts').update({status:'do_not_call'}).eq('id',this.session.attempt_id);await this.event('voice.dnc.persisted',{reason:'explicit_do_not_call'})}catch(e){await this.event('voice.dnc.persistence_failed',{message:String(e?.message||'DNC persistence failed.').slice(0,300)})}}
 async interrupt(reason,detectedAt=this.now()){const c=this.current;if(!c||c.interrupted)return;const start=Math.min(this.now(),Number(detectedAt)||this.now());this.generationEpoch++;c.interrupted=true;c.abort.abort(reason);try{this.tts.clear()}catch{};const clearAt=this.now();try{this.transport.clear()}catch{};const clearMs=Math.max(0,clearAt-start);await this.recordLatency(c.turnId,{speech_start_to_clear_ms:clearMs,barge_in_detected_at_ms:Math.max(0,start-this.startedAt)});if(c.sentText.trim()&&!c.persisted){await this.transcript('agent',c.sentText.trim(),{startMs:c.agentStartMs,endMs:Math.max(c.agentStartMs,this.now()-this.startedAt),providerSlug:this.tts.slug,metadata:{phase:7,turn_id:c.turnId,interrupted:true,reason,playback_confirmed:false}});c.persisted=true;this.history.push({role:'assistant',content:c.sentText.trim()});this.history=historyTrim(this.history);this.conversationState=recordAgentTurn(this.conversationState,c.sentText,c.strategy)}await this.persistConversationState(false);await this.patch({status:'interrupted',tts_state:'cancelled',interruption_count:(this.session.interruption_count||0)+1,last_agent_response:c.sentText.trim(),current_turn_id:null},true);await this.event('voice.barge_in',{turnId:c.turnId,reason,speechStartToClearMs:clearMs});this.current=null}
 async generateAgentTurn(userText,{opening=false,userAlreadyInHistory=false,userFinalAt=this.now(),repairReason=null,sttFinalMs=null,decision=null,directive='',endAfterPlayback=false,terminationReason=null}={}){
  if(this.closed)return;if(this.turnNo>=this.maxTurns)return this.fail('session',Object.assign(new Error('Turn limit reached.'),{code:'TURN_LIMIT'}));this.turnNo+=1;const turnId=`${this.session.id}:${this.turnNo}:${crypto.randomUUID().slice(0,8)}`;const epoch=++this.generationEpoch;const abort=new AbortController();const c={turnId,epoch,abort,interrupted:false,ttsStarted:false,ttsFlushed:false,sentText:'',buffer:'',agentStartMs:Math.max(0,this.now()-this.startedAt),userFinalAt,firstTokenLatencyMs:null,ttsFirstAudioLatencyMs:null,persisted:false,repairCount:repairReason?1:0,sttFinalMs,strategy:decision?.strategy||'opening',endAfterPlayback,terminationReason,complianceMs:0,complianceCalls:0};this.current=c;
  await this.patch({turn_no:this.turnNo,current_turn_id:turnId,status:'thinking',tts_state:'idle'},true);if(Number.isFinite(sttFinalMs))await this.recordLatency(turnId,{stt_final_ms:sttFinalMs});await this.event('voice.turn.started',{turnId,turnNo:this.turnNo,opening,strategy:c.strategy});
  const llmHistory=historyTrim(userAlreadyInHistory?this.history.slice(0,-1):this.history);let prompt=[userText,directive].filter(Boolean).join('\n\n');if(repairReason)prompt=`${prompt}\n\nCOMPLIANCE CORRECTION: The previous draft was blocked. Produce a new short answer that avoids these violations: ${repairReason}. Use only verified knowledge.`;
  try{
   for await(const token of this.llm.streamResponse({system:this.system,history:llmHistory,user:prompt,signal:abort.signal})){
    if(this.closed||epoch!==this.generationEpoch||c.interrupted)return;if(c.firstTokenLatencyMs==null&&token.firstTokenLatencyMs!=null){c.firstTokenLatencyMs=token.firstTokenLatencyMs;await this.recordLatency(turnId,{llm_first_token_ms:c.firstTokenLatencyMs})}c.buffer+=token.delta;if(c.buffer.length+c.sentText.length>600)c.buffer=c.buffer.slice(0,Math.max(0,600-c.sentText.length));const split=splitSpeakable(c.buffer,false);c.buffer=split.rest;for(const chunk of split.chunks){const ok=await this.validateAndSpeak(c,chunk,userText);if(!ok)return}}
   if(this.closed||epoch!==this.generationEpoch||c.interrupted)return;const split=splitSpeakable(c.buffer,true);c.buffer='';for(const chunk of split.chunks){const ok=await this.validateAndSpeak(c,chunk,userText);if(!ok)return}if(!c.sentText.trim()){await this.complianceRepair(c,userText,'empty_or_blocked_response',decision,directive);return}this.tts.flush();c.ttsFlushed=true;const evalResult=evaluateHumanness(c.sentText,{companyName:'AdLift',prospectText:userText,state:this.conversationState});await this.event('voice.humanness.evaluated',{turnId,score:evalResult.score,issues:evalResult.issues});await this.patch({last_agent_response:c.sentText.trim(),tts_state:'speaking'});
  }catch(e){if(e?.name==='AbortError'||c.interrupted||epoch!==this.generationEpoch)return;await this.providerFailure('llm',e)}
 }
 async validateAndSpeak(c,chunk,userText){if(!chunk.trim())return true;const validationStarted=this.now();const verdict=await this.llm.validate({candidate:chunk,hardRules:this.hard,knowledge:this.context.knowledge,signal:c.abort.signal});const complianceMs=Math.max(0,this.now()-validationStarted);c.complianceMs+=complianceMs;c.complianceCalls+=1;await this.recordLatency(c.turnId,{compliance_ms:c.complianceMs,compliance_calls:c.complianceCalls});if(c.epoch!==this.generationEpoch||c.interrupted)return false;if(!verdict.allowed){await this.patch({compliance_state:{blocked:true,turn_id:c.turnId,violations:verdict.violations,unsupported_claims:verdict.unsupportedClaims}});await this.event('voice.compliance.blocked',{turnId:c.turnId,violations:verdict.violations,unsupportedClaims:verdict.unsupportedClaims,latencyMs:complianceMs});await this.complianceRepair(c,userText,[...verdict.violations,...verdict.unsupportedClaims].join('; '),null,'');return false}c.sentText+=(c.sentText?' ':'')+chunk.trim();c.ttsStarted=true;this.tts.speak(chunk.trim()+' ');await this.patch({status:'speaking',tts_state:'buffering',compliance_state:{blocked:false,turn_id:c.turnId}});return true}
 async complianceRepair(c,userText,reason,decision=null,directive=''){if(c.interrupted)return;c.abort.abort('compliance_regenerate');try{this.tts.clear()}catch{};try{this.transport.clear()}catch{};this.current=null;if(c.repairCount>=1){await this.safeFallback('I don’t have enough verified info to answer that safely.',c.endAfterPlayback,c.terminationReason);return}await this.generateAgentTurn(userText,{repairReason:String(reason||'compliance_block').slice(0,500),userAlreadyInHistory:true,userFinalAt:c.userFinalAt,sttFinalMs:c.sttFinalMs,decision:decision||{strategy:c.strategy},directive,endAfterPlayback:c.endAfterPlayback,terminationReason:c.terminationReason})}
 async safeFallback(text,endAfterPlayback=false,terminationReason=null){if(this.closed)return;const abort=new AbortController();const verdict=await this.llm.validate({candidate:text,hardRules:this.hard,knowledge:this.context.knowledge,signal:abort.signal});if(!verdict.allowed)return this.fail('compliance',Object.assign(new Error('Safe fallback failed compliance validation.'),{code:'COMPLIANCE_FALLBACK_BLOCKED'}));const turnId=`${this.session.id}:fallback:${crypto.randomUUID().slice(0,8)}`;const c={turnId,abort,interrupted:false,ttsStarted:true,ttsFlushed:true,sentText:text,agentStartMs:Math.max(0,this.now()-this.startedAt),persisted:false,userFinalAt:this.now(),strategy:'safe_fallback',endAfterPlayback,terminationReason};this.current=c;this.tts.speak(text);this.tts.flush();await this.patch({status:'speaking',tts_state:'speaking',last_agent_response:text})}
 onTtsAudio(buffer){const c=this.current;if(!c||c.interrupted||this.closed)return;this.transport.sendAudio(buffer,c.turnId);this.patch({status:'speaking',tts_state:'speaking'})}
 async onFirstAudio({latencyMs}){const c=this.current;if(!c)return;c.ttsFirstAudioLatencyMs=latencyMs;const total=Math.max(0,this.now()-c.userFinalAt);const values={tts_first_audio_ms:latencyMs,speech_end_to_first_audio_ms:total,total_turn_ms:total};if(c.strategy==='opening'&&this.connectedAtMs)values.connected_to_first_audio_ms=Math.max(0,this.now()-this.connectedAtMs);await this.recordLatency(c.turnId,values)}
 onTtsFlushed(){const c=this.current;if(!c||c.interrupted)return;this.transport.mark(c.turnId)}
 async onMark(evt){const mark=this.transport.acknowledgeMark(evt);if(!mark)return;const c=this.current;if(!c||mark.turnId!==c.turnId||c.interrupted)return;if(c.sentText.trim()&&!c.persisted){await this.transcript('agent',c.sentText.trim(),{startMs:c.agentStartMs,endMs:Math.max(c.agentStartMs,this.now()-this.startedAt),providerSlug:this.tts.slug,metadata:{phase:7,turn_id:c.turnId,interrupted:false,playback_confirmed:true,strategy:c.strategy}});c.persisted=true;this.history.push({role:'assistant',content:c.sentText.trim()});this.history=historyTrim(this.history);this.conversationState=recordAgentTurn(this.conversationState,c.sentText,c.strategy);await this.persistConversationState(false)}await this.patch({status:'listening',tts_state:'idle',last_agent_response:c.sentText.trim(),current_turn_id:null},true);await this.event('voice.turn.completed',{turnId:c.turnId,turnNo:this.turnNo,strategy:c.strategy});this.current=null;if(c.endAfterPlayback)await this.stop(c.terminationReason||'conversation_ended')}
 async recordLatency(turnId,values){const current=this.session.latency_metrics||{};const next={...current,[turnId]:{...(current[turnId]||{}),...values,at:new Date().toISOString()}};const keys=Object.keys(next);while(keys.length>30)delete next[keys.shift()];await this.patch({latency_metrics:next})}
 async providerFailure(kind,e){if(this.closed)return;const err=compactError(e);const errors=[...(this.session.provider_errors||[]),{provider:kind,...err}].slice(-20);await this.patch({provider_errors:errors,provider_states:{...(this.session.provider_states||{}),[kind]:'failed'}},true);await this.event(`voice.${kind}.failed`,err);await this.fail(kind,e)}
 async fail(kind,e){if(this.closed)return;const err=compactError(e);const errors=this.session.provider_errors?.at(-1)?.code===err.code?this.session.provider_errors:[...(this.session.provider_errors||[]),{provider:kind,...err}].slice(-20);await this.patch({status:'failed',tts_state:kind==='tts'?'failed':'idle',provider_errors:errors,ended_at:new Date().toISOString()},true);await this.event('voice.session.failed',{provider:kind,...err});this.close('failed')}
 async stop(reason='stream_stop'){if(this.closed)return;if(reason&&this.conversationState&&!this.conversationState.termination_reason&&reason!=='twilio_stream_stop'&&reason!=='websocket_closed')this.conversationState.termination_reason=reason;await this.patch({status:'completed',tts_state:'idle',ended_at:new Date().toISOString(),current_turn_id:null,objection_state:{...(this.session.objection_state||{}),conversation_state:this.conversationState}},true);await this.event('voice.session.completed',{reason,turns:this.turnNo,terminationReason:this.conversationState?.termination_reason||null});this.close('completed')}
 close(){if(this.closed)return;this.closed=true;clearTimeout(this.sessionTimeout);clearTimeout(this.patchTimer);try{this.current?.abort?.abort('session_close')}catch{};try{this.stt.close()}catch{};try{this.tts.close()}catch{};try{this.transport.close()}catch{};try{this.socket?.close?.()}catch{}}
}
