import crypto from 'node:crypto';
import {buildTurnContext,hardRules,selectRelevantKnowledge} from './context.js';
import {DEFAULT_QUALITY_SETTINGS,initialConversationState,decideConversation,recordAgentTurn,buildOpeningDirective,buildTurnDirective,evaluateHumanness} from './conversation.js';

function compactError(e){return {code:String(e?.code||'VOICE_ERROR').slice(0,80),message:String(e?.message||'Voice provider failure.').slice(0,500),retry_after_ms:Number.isFinite(e?.retryAfterMs)?e.retryAfterMs:null,rate_limit:e?.rateLimit||null,at:new Date().toISOString()}}
function splitSpeakable(text,final=false){const chunks=[];let rest=text;const re=/^([\s\S]*?[.!?](?:\s+|$))/;while(true){const m=rest.match(re);if(!m)break;const c=m[1].trim();if(c)chunks.push(c);rest=rest.slice(m[1].length)}if(final&&rest.trim())return {chunks:[...chunks,rest.trim()],rest:''};return {chunks,rest}}
function historyTrim(h,max=8){return h.slice(Math.max(0,h.length-max))}
function average(values){const xs=values.filter(Number.isFinite);return xs.length?Math.round(xs.reduce((a,b)=>a+b,0)/xs.length):null}
function qualitySettings(context){const q=context?.campaign?.compliance_settings?.voice_quality||{};return {...DEFAULT_QUALITY_SETTINGS,...q,max_spoken_sentences:Math.max(1,Math.min(2,Number(q.max_spoken_sentences||DEFAULT_QUALITY_SETTINGS.max_spoken_sentences))),max_words:Math.max(15,Math.min(44,Number(q.max_words||DEFAULT_QUALITY_SETTINGS.max_words))),brush_off_limit:Math.max(1,Math.min(3,Number(q.brush_off_limit||DEFAULT_QUALITY_SETTINGS.brush_off_limit)))}}
function msFromMulawBytes(bytes){return Math.round(Math.max(0,Number(bytes)||0)/8)}
function rateLimitFallback(strategy){const map={opening:'Hey — I’ll keep it quick. How are you getting most of your business right now?',disarm_and_curiosity:'Yeah, fair. Are you mostly running on referrals right now?',respect_time:'Got it — I can keep it to ten seconds, or catch you another time.',validate_current_solution:'Makes sense. What’s working best for you for lead flow right now?',verified_price_only:'I don’t want to make up a number. Mind if I ask one quick question first?',graceful_exit:'Got it. Appreciate it — have a good one.',dnc_exit:'Understood. I’ll leave it there.'};return map[strategy]||'Gotcha — how are you getting most of your business right now?'}

export class VoiceOrchestrator{
 constructor({admin,session,context,providers,transport,socket,now=()=>Date.now(),maxSessionMs=30*60*1000,maxTurns=100}={}){
  this.admin=admin;this.session=session;this.context=context;this.providers=providers;this.transport=transport;this.socket=socket;this.now=now;this.maxSessionMs=maxSessionMs;this.maxTurns=maxTurns;this.startedAt=now();this.turnNo=session.turn_no||0;this.history=[];this.pendingFinal='';this.pendingFinalStart=null;this.pendingFinalEnd=null;this.pendingSpeechEndAt=null;this.pendingConfidence=[];this.pendingSttLatency=[];this.recentFinalSignatures=[];this.current=null;this.generationEpoch=0;this.closed=false;this.patchTimer=null;this.sessionPatch={};this.hard=hardRules(context);this.quality=qualitySettings(context);this.conversationState=initialConversationState(session?.objection_state?.conversation_state||{});this.connectedAtMs=null;this.lastLocalSpeechStartAt=null;this.lastLocalSpeechEndAt=null;this.lastInterruptionDetectedAt=null;this.backgroundTasks=new Set();
  this.stt=providers.stt(session.stt_provider_slug);this.llm=providers.llm(session.llm_provider_slug);this.tts=providers.tts(session.tts_provider_slug);
 }
 background(promise){const p=Promise.resolve(promise).catch(()=>{});this.backgroundTasks.add(p);p.finally(()=>this.backgroundTasks.delete(p));return p}
 async patch(patch,immediate=false){Object.assign(this.session,patch);Object.assign(this.sessionPatch,patch,{last_activity_at:new Date().toISOString()});if(immediate)return this.flushPatch();if(!this.patchTimer)this.patchTimer=setTimeout(()=>this.flushPatch().catch(()=>{}),150)}
 async flushPatch(){clearTimeout(this.patchTimer);this.patchTimer=null;const patch=this.sessionPatch;this.sessionPatch={};if(!Object.keys(patch).length)return;await this.admin.from('ai_voice_sessions').update(patch).eq('id',this.session.id)}
 async event(type,payload={}){await this.admin.from('ai_call_events').insert({attempt_id:this.session.attempt_id,event_type:type,event_source:'voice_worker',payload})}
 async transcript(speaker,text,{startMs=0,endMs=null,confidence=null,providerSlug=null,providerSegmentId=null,metadata={}}={}){if(!String(text||'').trim())return null;const {data,error}=await this.admin.rpc('ai_append_transcript_segment',{p_attempt_id:this.session.attempt_id,p_speaker:speaker,p_start_ms:Math.max(0,startMs|0),p_end_ms:endMs==null?null:Math.max(0,endMs|0),p_text:String(text),p_confidence:confidence,p_provider_slug:providerSlug,p_provider_segment_id:providerSegmentId,p_metadata:metadata});if(error)throw error;return data}
 async persistConversationState(immediate=false){await this.patch({objection_state:{...(this.session.objection_state||{}),conversation_state:this.conversationState}},immediate)}
 async start(){
  if(this.closed)throw new Error('session closed');const llmStatus=this.llm.status?.()||{},ttsStatus=this.tts.status?.()||{},sttStatus=this.stt.status?.()||{};
  await this.patch({status:'connecting',provider_states:{stt:'connecting',llm:'ready',tts:'connecting',llm_model:llmStatus.model||null,tts_voice:ttsStatus.voice||ttsStatus.model||null,tts_speed:ttsStatus.speed||null,stt_model:sttStatus.model||null}},true);
  await Promise.all([
   this.stt.connect({onState:s=>this.patch({provider_states:{...(this.session.provider_states||{}),stt:s}}),onSpeechStarted:e=>this.onSpeechStarted(e),onInterim:e=>this.onInterim(e),onFinal:e=>this.onFinal(e),onUtteranceEnd:e=>this.onUtteranceEnd(e),onError:e=>this.providerFailure('stt',e),onClose:e=>{if(!this.closed)this.providerFailure('stt',Object.assign(new Error('STT disconnected'),{code:'STT_DISCONNECT',detail:e}))}}),
   this.tts.connect({onState:s=>this.patch({provider_states:{...(this.session.provider_states||{}),tts:s},tts_state:s==='clearing'?'clearing':this.current?.ttsStarted?'speaking':'idle'}),onAudio:b=>this.onTtsAudio(b),onFirstAudio:m=>this.onFirstAudio(m),onFlushed:()=>this.onTtsFlushed(),onError:e=>this.providerFailure('tts',e),onClose:e=>{if(!this.closed)this.providerFailure('tts',Object.assign(new Error('TTS disconnected'),{code:'TTS_DISCONNECT',detail:e}))}})
  ]);
  this.connectedAtMs=this.now();await this.patch({status:'listening',connected_at:new Date().toISOString(),provider_states:{...(this.session.provider_states||{}),stt:'connected',llm:'ready',tts:'connected'},objection_state:{...(this.session.objection_state||{}),conversation_state:this.conversationState}},true);await this.event('voice.session.connected',{sessionId:this.session.id,providers:{stt:this.session.stt_provider_slug,llm:this.session.llm_provider_slug,tts:this.session.tts_provider_slug},model:llmStatus.model||null,voice:ttsStatus.voice||null,ttsSpeed:ttsStatus.speed||null,quality:this.quality});
  this.sessionTimeout=setTimeout(()=>this.fail('session',Object.assign(new Error('Maximum controlled voice session duration reached.'),{code:'SESSION_TIMEOUT'})),this.maxSessionMs);
  const openingDecision={state:this.conversationState,strategy:'opening',terminate:false,repeatedStrategy:false};await this.generateAgentTurn('The phone call has just connected.',{opening:true,decision:openingDecision,directive:buildOpeningDirective(this.conversationState,this.context.prospect),userFinalAt:this.connectedAtMs});
 }
 onMedia(evt){if(this.closed)return;const m=this.transport.ingest(evt);if(m.duplicate||m.ignored)return;if(m.speechStarted){this.lastLocalSpeechStartAt=m.detectedAtMs||this.now();this.lastLocalSpeechEndAt=null;if(this.current?.ttsStarted)this.interrupt('audio_vad',this.lastLocalSpeechStartAt)}if(m.speechEnded){this.lastLocalSpeechEndAt=m.speechEndedAtMs||this.now();if(this.pendingFinal.trim())this.pendingSpeechEndAt=this.lastLocalSpeechEndAt}if(m.audio)this.stt.sendAudio(m.audio);if(this.now()-this.startedAt>this.maxSessionMs)this.fail('session',Object.assign(new Error('Session timeout.'),{code:'SESSION_TIMEOUT'}))}
 async onSpeechStarted(e={}){if(!this.current?.ttsStarted)return;const at=e.atMs||this.now();if(this.lastLocalSpeechStartAt&&Math.abs(at-this.lastLocalSpeechStartAt)<400)return;await this.interrupt('stt_speech_started',at)}
 async onInterim(e){if(this.closed)return;await this.patch({interim_transcript:e.text,status:this.current?.ttsStarted?'speaking':'listening'})}
 localSpeechEndFor(receivedAt){const end=this.lastLocalSpeechEndAt,start=this.lastLocalSpeechStartAt;if(!Number.isFinite(end)||!Number.isFinite(start)||end<start)return null;if(Number.isFinite(receivedAt)&&(receivedAt-end<0||receivedAt-end>2500))return null;return end}
 async onFinal(e){if(this.closed)return;this.pendingFinal=[this.pendingFinal,e.text].filter(Boolean).join(' ').trim();this.pendingFinalStart=this.pendingFinalStart??e.startMs;this.pendingFinalEnd=e.endMs;const localEnd=this.localSpeechEndFor(e.receivedAtMs);if(localEnd){this.pendingSpeechEndAt=Math.max(this.pendingSpeechEndAt||0,localEnd);this.pendingSttLatency.push(Math.max(0,e.receivedAtMs-localEnd))}this.pendingConfidence.push(e.confidence);await this.patch({interim_transcript:e.speechFinal?'':this.pendingFinal});if(e.speechFinal)await this.commitProspectTurn(e.providerSegmentId,e.receivedAtMs)}
 async onUtteranceEnd(e={}){if(this.pendingFinal.trim())await this.commitProspectTurn(null,e.atMs||this.now())}
 async commitProspectTurn(providerSegmentId,fallbackAt=null){const text=this.pendingFinal.trim();if(!text)return;const startMs=this.pendingFinalStart??Math.max(0,this.now()-this.startedAt);const endMs=this.pendingFinalEnd??Math.max(startMs,this.now()-this.startedAt);const speechEndAt=this.pendingSpeechEndAt||this.localSpeechEndFor(fallbackAt)||fallbackAt||this.now();const hasGroundTruth=Boolean(this.pendingSpeechEndAt||this.localSpeechEndFor(fallbackAt));const vals=this.pendingConfidence.filter(Number.isFinite);const confidence=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null;const sttFinalMs=hasGroundTruth?average(this.pendingSttLatency):null;const signature=`${startMs}:${endMs}:${text}`;this.pendingFinal='';this.pendingFinalStart=null;this.pendingFinalEnd=null;this.pendingSpeechEndAt=null;this.pendingConfidence=[];this.pendingSttLatency=[];
  if(this.recentFinalSignatures.includes(signature)){await this.patch({interim_transcript:''});return}this.recentFinalSignatures.push(signature);if(this.recentFinalSignatures.length>50)this.recentFinalSignatures.shift();if(this.current)this.interrupt('new_final_turn',this.now());const last=this.history[this.history.length-1];if(last?.role==='user'&&last.content===text)return;
  await this.transcript('prospect',text,{startMs,endMs,confidence,providerSlug:this.stt.slug,providerSegmentId,metadata:{phase:7,stt_final_latency_ms:sttFinalMs,latency_source:hasGroundTruth?'twilio_vad_wall_clock':'unavailable'}});this.history.push({role:'user',content:text});this.history=historyTrim(this.history);
  const decision=decideConversation(this.conversationState,text,this.quality);this.conversationState=decision.state;await this.persistConversationState(false);await this.patch({interim_transcript:'',last_prospect_utterance:text,status:'thinking'});if(decision.classification.type==='explicit_do_not_call')await this.persistDnc(text);const directive=buildTurnDirective(decision,this.quality);await this.event('voice.conversation.strategy',{type:decision.classification.type,strategy:decision.strategy,brushOffCount:this.conversationState.brush_off_count,terminate:decision.terminate});const recovery=Boolean(this.lastInterruptionDetectedAt&&speechEndAt>=this.lastInterruptionDetectedAt);await this.generateAgentTurn(text,{userAlreadyInHistory:true,userFinalAt:speechEndAt,sttFinalMs,decision,directive,endAfterPlayback:decision.terminate,terminationReason:decision.terminationReason,recoveryFromInterruption:recovery})
 }
 async persistDnc(text){try{const {error}=await this.admin.from('ai_suppressions').insert({prospect_record_id:this.session.prospect_record_id,phone_e164:this.context.attempt?.phone_e164||null,campaign_id:null,scope:'global',suppression_type:'do_not_call',reason:String(text||'Explicit do-not-call request').slice(0,500),source_attempt_id:this.session.attempt_id,active:true});if(error)throw error;await this.admin.from('ai_call_attempts').update({status:'do_not_call'}).eq('id',this.session.attempt_id);await this.event('voice.dnc.persisted',{reason:'explicit_do_not_call'})}catch(e){await this.event('voice.dnc.persistence_failed',{message:String(e?.message||'DNC persistence failed.').slice(0,300)})}}
 interrupt(reason,detectedAt=this.now()){const c=this.current;if(!c||c.interrupted)return false;const start=Math.min(this.now(),Number(detectedAt)||this.now());this.lastInterruptionDetectedAt=start;this.generationEpoch++;c.interrupted=true;c.abort.abort(reason);try{this.tts.clear()}catch{};try{this.transport.clear()}catch{};const clearAt=this.now(),clearMs=Math.max(0,clearAt-start);this.current=null;this.session.interruption_count=(this.session.interruption_count||0)+1;this.background(this.finishInterrupt(c,reason,start,clearMs));return true}
 async finishInterrupt(c,reason,start,clearMs){await this.recordLatency(c.turnId,{interruption_to_clear_ms:clearMs,speech_start_to_clear_ms:clearMs,barge_in_detected_at_ms:Math.max(0,start-this.startedAt),acknowledged_audio_ms:msFromMulawBytes(c.ackedAudioBytes),sent_audio_ms:msFromMulawBytes(c.sentAudioBytes)});await this.event('voice.agent.interrupted_delivery',{turnId:c.turnId,reason,generated_text:c.generatedText.trim(),approved_text:c.approvedText.trim(),queued_for_tts:c.queuedText.trim(),sent_to_twilio_audio_ms:msFromMulawBytes(c.sentAudioBytes),acknowledged_playback_audio_ms:msFromMulawBytes(c.ackedAudioBytes),interrupted_before_completion:true,playback_confirmed:false});await this.persistConversationState(false);await this.patch({status:'interrupted',tts_state:'cancelled',interruption_count:this.session.interruption_count,last_agent_response:c.ackedComplete?c.approvedText.trim():'',current_turn_id:null},true);await this.event('voice.barge_in',{turnId:c.turnId,reason,interruptionToClearMs:clearMs})}
 async generateAgentTurn(userText,{opening=false,userAlreadyInHistory=false,userFinalAt=this.now(),repairReason=null,sttFinalMs=null,decision=null,directive='',endAfterPlayback=false,terminationReason=null,recoveryFromInterruption=false}={}){
  if(this.closed)return;if(this.turnNo>=this.maxTurns)return this.fail('session',Object.assign(new Error('Turn limit reached.'),{code:'TURN_LIMIT'}));this.turnNo+=1;const turnId=`${this.session.id}:${this.turnNo}:${crypto.randomUUID().slice(0,8)}`;const epoch=++this.generationEpoch;const abort=new AbortController();const strategy=decision?.strategy||'opening';const state=decision?.state||this.conversationState;const baseHistory=userAlreadyInHistory?this.history.slice(0,-1):this.history;const request=buildTurnContext(this.context,{prospectText:userText,strategy,state,directive,history:baseHistory});let prompt=request.user;if(repairReason)prompt=`${prompt}\n\nCORRECTION: Previous draft was blocked. Answer safely without the blocked claim: ${String(repairReason).slice(0,300)}`;const c={turnId,epoch,abort,interrupted:false,ttsStarted:false,ttsFlushed:false,generatedText:'',approvedText:'',queuedText:'',buffer:'',agentStartMs:Math.max(0,this.now()-this.startedAt),userFinalAt,firstTokenLatencyMs:null,ttsFirstAudioLatencyMs:null,persisted:false,repairCount:repairReason?1:0,sttFinalMs,strategy,endAfterPlayback,terminationReason,complianceMs:0,complianceCalls:0,relevantKnowledge:request.knowledge,sentAudioBytes:0,ackedAudioBytes:0,nextProgressMarkBytes:3200,ackedComplete:false,recoveryFromInterruption};this.current=c;
  await this.patch({turn_no:this.turnNo,current_turn_id:turnId,status:'thinking',tts_state:'idle'},true);await this.recordLatency(turnId,{stt_final_ms:Number.isFinite(sttFinalMs)?sttFinalMs:null,prompt_input_tokens_estimate:request.estimatedInputTokens,prompt_input_chars:request.inputChars,selected_model:this.llm.status?.().model||null});await this.event('voice.turn.started',{turnId,turnNo:this.turnNo,opening,strategy,promptInputTokensEstimate:request.estimatedInputTokens,promptInputChars:request.inputChars,historyMessages:request.history.length,relevantKnowledge:request.knowledge.length});
  try{
   for await(const token of this.llm.streamResponse({system:request.system,history:request.history,user:prompt,signal:abort.signal})){
    if(this.closed||epoch!==this.generationEpoch||c.interrupted)return;if(token.rateLimitRetry)await this.event('voice.llm.rate_limit_retry',{turnId,...token.rateLimitRetry});if(c.firstTokenLatencyMs==null&&token.firstTokenLatencyMs!=null){c.firstTokenLatencyMs=token.firstTokenLatencyMs;await this.recordLatency(turnId,{llm_first_token_ms:c.firstTokenLatencyMs,rate_limit_retry_ms:token.rateLimitRetry?.retryAfterMs||null})}c.generatedText+=token.delta;c.buffer+=token.delta;if(c.buffer.length+c.approvedText.length>420)c.buffer=c.buffer.slice(0,Math.max(0,420-c.approvedText.length));const split=splitSpeakable(c.buffer,false);c.buffer=split.rest;for(const chunk of split.chunks){const ok=await this.validateAndSpeak(c,chunk,userText);if(!ok)return}}
   if(this.closed||epoch!==this.generationEpoch||c.interrupted)return;const split=splitSpeakable(c.buffer,true);c.buffer='';for(const chunk of split.chunks){const ok=await this.validateAndSpeak(c,chunk,userText);if(!ok)return}if(!c.approvedText.trim()){await this.complianceRepair(c,userText,'empty_or_blocked_response',decision,directive);return}this.tts.flush();c.ttsFlushed=true;const evalResult=evaluateHumanness(c.approvedText,{companyName:'AdLift',prospectText:userText,state:this.conversationState});await this.event('voice.humanness.evaluated',{turnId,score:evalResult.score,issues:evalResult.issues});await this.patch({last_agent_response:c.approvedText.trim(),tts_state:'speaking'});
  }catch(e){if(e?.name==='AbortError'||c.interrupted||epoch!==this.generationEpoch)return;if(e?.code==='LLM_RATE_LIMIT')return this.handleRateLimit(c,e);await this.providerFailure('llm',e)}
 }
 async validateAndSpeak(c,chunk,userText){if(!chunk.trim())return true;const validationStarted=this.now();let verdict;try{verdict=await this.llm.validate({candidate:chunk,hardRules:this.hard,knowledge:c.relevantKnowledge,signal:c.abort.signal})}catch(e){if(e?.name==='AbortError'||c.interrupted)return false;if(e?.code==='LLM_RATE_LIMIT')return this.handleRateLimit(c,e);throw e}const complianceMs=Math.max(0,this.now()-validationStarted);c.complianceMs+=complianceMs;c.complianceCalls+=1;await this.recordLatency(c.turnId,{compliance_ms:c.complianceMs,compliance_calls:c.complianceCalls,last_compliance_chunk_ms:complianceMs});if(c.epoch!==this.generationEpoch||c.interrupted)return false;if(!verdict.allowed){await this.patch({compliance_state:{blocked:true,turn_id:c.turnId,violations:verdict.violations,unsupported_claims:verdict.unsupportedClaims}});await this.event('voice.compliance.blocked',{turnId:c.turnId,violations:verdict.violations,unsupportedClaims:verdict.unsupportedClaims,latencyMs:complianceMs});await this.complianceRepair(c,userText,[...verdict.violations,...verdict.unsupportedClaims].join('; '),null,'');return false}c.approvedText+=(c.approvedText?' ':'')+chunk.trim();c.queuedText+=(c.queuedText?' ':'')+chunk.trim();c.ttsStarted=true;this.tts.speak(chunk.trim()+' ');await this.patch({status:'speaking',tts_state:'buffering',compliance_state:{blocked:false,turn_id:c.turnId}});return true}
 async handleRateLimit(c,e){if(c.interrupted||this.closed)return false;const err=compactError(e);await this.event('voice.llm.rate_limited',{turnId:c.turnId,...err});await this.patch({provider_errors:[...(this.session.provider_errors||[]),{provider:'llm',...err}].slice(-20),provider_states:{...(this.session.provider_states||{}),llm:'rate_limited'}},true);c.abort.abort('rate_limit_fallback');try{this.tts.clear()}catch{};try{this.transport.clear()}catch{};if(this.current===c)this.current=null;const fallback=rateLimitFallback(c.strategy);const spoken=await this.safeFallback(fallback,c.endAfterPlayback,c.terminationReason||'llm_rate_limited',{userFinalAt:c.userFinalAt,strategy:'rate_limit_fallback',recoveryFromInterruption:c.recoveryFromInterruption,rateLimit:true});if(!spoken){this.conversationState.termination_reason='llm_rate_limited';await this.stop('llm_rate_limited')}return false}
 async complianceRepair(c,userText,reason,decision=null,directive=''){if(c.interrupted)return;c.abort.abort('compliance_regenerate');try{this.tts.clear()}catch{};try{this.transport.clear()}catch{};if(this.current===c)this.current=null;if(c.repairCount>=1){await this.safeFallback('I don’t have enough verified info to answer that safely.',c.endAfterPlayback,c.terminationReason,{userFinalAt:c.userFinalAt,strategy:'safe_fallback'});return}await this.generateAgentTurn(userText,{repairReason:String(reason||'compliance_block').slice(0,300),userAlreadyInHistory:true,userFinalAt:c.userFinalAt,sttFinalMs:c.sttFinalMs,decision:decision||{strategy:c.strategy,state:this.conversationState},directive,endAfterPlayback:c.endAfterPlayback,terminationReason:c.terminationReason,recoveryFromInterruption:c.recoveryFromInterruption})}
 async safeFallback(text,endAfterPlayback=false,terminationReason=null,{userFinalAt=this.now(),strategy='safe_fallback',recoveryFromInterruption=false,rateLimit=false}={}){if(this.closed)return false;const abort=new AbortController();const knowledge=selectRelevantKnowledge(this.context,{prospectText:text,strategy,state:this.conversationState});let verdict;try{verdict=await this.llm.validate({candidate:text,hardRules:this.hard,knowledge,signal:abort.signal})}catch(e){await this.event('voice.fallback.unavailable',{reason:rateLimit?'rate_limit':'provider_failure',code:e?.code||'VALIDATOR_FAILURE',retryAfterMs:e?.retryAfterMs||null});return false}if(!verdict.allowed){await this.event('voice.fallback.blocked',{violations:verdict.violations,unsupportedClaims:verdict.unsupportedClaims});return false}const turnId=`${this.session.id}:fallback:${crypto.randomUUID().slice(0,8)}`;const c={turnId,abort,interrupted:false,ttsStarted:true,ttsFlushed:true,generatedText:text,approvedText:text,queuedText:text,agentStartMs:Math.max(0,this.now()-this.startedAt),persisted:false,userFinalAt,strategy,endAfterPlayback,terminationReason,relevantKnowledge:knowledge,sentAudioBytes:0,ackedAudioBytes:0,nextProgressMarkBytes:3200,ackedComplete:false,recoveryFromInterruption};this.current=c;this.tts.speak(text);this.tts.flush();await this.patch({status:'speaking',tts_state:'speaking',provider_states:{...(this.session.provider_states||{}),llm:rateLimit?'rate_limited_fallback':'ready'},last_agent_response:text});return true}
 onTtsAudio(buffer){const c=this.current;if(!c||c.interrupted||this.closed)return;if(this.transport.sendAudio(buffer,c.turnId)){c.sentAudioBytes+=buffer.length;if(c.sentAudioBytes>=c.nextProgressMarkBytes){this.transport.mark(c.turnId,{kind:'progress',audioBytes:c.sentAudioBytes});c.nextProgressMarkBytes+=3200}}this.patch({status:'speaking',tts_state:'speaking'})}
 async onFirstAudio({latencyMs}){const c=this.current;if(!c)return;c.ttsFirstAudioLatencyMs=latencyMs;const total=Math.max(0,this.now()-c.userFinalAt);const values={tts_first_audio_ms:latencyMs,speech_end_to_first_audio_ms:total,total_turn_ms:total};if(c.strategy==='opening'&&this.connectedAtMs)values.connected_to_first_audio_ms=Math.max(0,this.now()-this.connectedAtMs);if(c.recoveryFromInterruption)values.interruption_speech_end_to_first_audio_ms=total;await this.recordLatency(c.turnId,values)}
 onTtsFlushed(){const c=this.current;if(!c||c.interrupted)return;this.transport.mark(c.turnId,{kind:'final',audioBytes:c.sentAudioBytes})}
 async onMark(evt){const mark=this.transport.acknowledgeMark(evt);if(!mark)return;const c=this.current;if(!c||mark.turnId!==c.turnId||c.interrupted)return;const kind=mark.metadata?.kind||'final';if(kind==='progress'){c.ackedAudioBytes=Math.max(c.ackedAudioBytes,Number(mark.metadata?.audioBytes||0));await this.recordLatency(c.turnId,{acknowledged_audio_ms:msFromMulawBytes(c.ackedAudioBytes)});return}c.ackedAudioBytes=Math.max(c.ackedAudioBytes,Number(mark.metadata?.audioBytes||c.sentAudioBytes));c.ackedComplete=true;if(c.approvedText.trim()&&!c.persisted){await this.transcript('agent',c.approvedText.trim(),{startMs:c.agentStartMs,endMs:Math.max(c.agentStartMs,this.now()-this.startedAt),providerSlug:this.tts.slug,metadata:{phase:7,turn_id:c.turnId,generated_text:c.generatedText.trim(),approved_text:c.approvedText.trim(),queued_for_tts:c.queuedText.trim(),sent_to_twilio:true,acknowledged_playback:true,interrupted_before_completion:false,strategy:c.strategy}});c.persisted=true;this.history.push({role:'assistant',content:c.approvedText.trim()});this.history=historyTrim(this.history);this.conversationState=recordAgentTurn(this.conversationState,c.approvedText,c.strategy);await this.persistConversationState(false)}await this.patch({status:'listening',tts_state:'idle',provider_states:{...(this.session.provider_states||{}),llm:'ready'},last_agent_response:c.approvedText.trim(),current_turn_id:null},true);await this.event('voice.turn.completed',{turnId:c.turnId,turnNo:this.turnNo,strategy:c.strategy,audibleText:c.approvedText.trim()});this.current=null;if(c.endAfterPlayback)await this.stop(c.terminationReason||'conversation_ended')}
 async recordLatency(turnId,values){const current=this.session.latency_metrics||{};const next={...current,[turnId]:{...(current[turnId]||{}),...values,at:new Date().toISOString()}};const keys=Object.keys(next);while(keys.length>30)delete next[keys.shift()];await this.patch({latency_metrics:next})}
 async providerFailure(kind,e){if(this.closed)return;const err=compactError(e);const errors=[...(this.session.provider_errors||[]),{provider:kind,...err}].slice(-20);const terminationReason=kind==='llm'?'llm_provider_failed':kind==='tts'?'tts_failed':kind==='stt'?'stt_failed':`${kind}_failed`;this.conversationState.termination_reason=terminationReason;await this.patch({provider_errors:errors,provider_states:{...(this.session.provider_states||{}),[kind]:'failed'},objection_state:{...(this.session.objection_state||{}),conversation_state:this.conversationState}},true);await this.event(`voice.${kind}.failed`,{...err,terminationReason});await this.fail(kind,e,terminationReason)}
 async fail(kind,e,terminationReason=null){if(this.closed)return;const err=compactError(e);const errors=this.session.provider_errors?.at(-1)?.code===err.code?this.session.provider_errors:[...(this.session.provider_errors||[]),{provider:kind,...err}].slice(-20);if(terminationReason)this.conversationState.termination_reason=terminationReason;await this.patch({status:'failed',tts_state:kind==='tts'?'failed':'idle',provider_errors:errors,ended_at:new Date().toISOString(),objection_state:{...(this.session.objection_state||{}),conversation_state:this.conversationState}},true);await this.event('voice.session.failed',{provider:kind,...err,terminationReason:this.conversationState.termination_reason});this.close('failed')}
 async stop(reason='stream_stop'){if(this.closed)return;if(reason&&this.conversationState&&!this.conversationState.termination_reason&&reason!=='twilio_stream_stop'&&reason!=='websocket_closed')this.conversationState.termination_reason=reason;await this.patch({status:'completed',tts_state:'idle',ended_at:new Date().toISOString(),current_turn_id:null,objection_state:{...(this.session.objection_state||{}),conversation_state:this.conversationState}},true);await this.event('voice.session.completed',{reason,turns:this.turnNo,terminationReason:this.conversationState?.termination_reason||null});this.close('completed')}
 close(){if(this.closed)return;this.closed=true;clearTimeout(this.sessionTimeout);clearTimeout(this.patchTimer);try{this.current?.abort?.abort('session_close')}catch{};try{this.stt.close()}catch{};try{this.tts.close()}catch{};try{this.transport.close()}catch{};try{this.socket?.close?.()}catch{}}
}
