import crypto from 'node:crypto';
import {buildSystemPrompt,hardRules} from './context.js';

const terminalStatuses=new Set(['completed','failed']);
function compactError(e){return {code:String(e?.code||'VOICE_ERROR').slice(0,80),message:String(e?.message||'Voice provider failure.').slice(0,500),at:new Date().toISOString()}}
function splitSpeakable(text,final=false){const chunks=[];let rest=text;const re=/^([\s\S]*?[.!?](?:\s+|$))/;while(true){const m=rest.match(re);if(!m)break;const c=m[1].trim();if(c)chunks.push(c);rest=rest.slice(m[1].length)}if(final&&rest.trim())return {chunks:[...chunks,rest.trim()],rest:''};return {chunks,rest}}
function historyTrim(h,max=24){return h.slice(Math.max(0,h.length-max))}

export class VoiceOrchestrator{
 constructor({admin,session,context,providers,transport,socket,now=()=>Date.now(),maxSessionMs=30*60*1000,maxTurns=100}={}){
  this.admin=admin;this.session=session;this.context=context;this.providers=providers;this.transport=transport;this.socket=socket;this.now=now;this.maxSessionMs=maxSessionMs;this.maxTurns=maxTurns;this.startedAt=now();this.turnNo=session.turn_no||0;this.history=[];this.pendingFinal='';this.pendingFinalStart=null;this.pendingFinalEnd=null;this.pendingConfidence=[];this.current=null;this.generationEpoch=0;this.closed=false;this.patchTimer=null;this.sessionPatch={};this.system=buildSystemPrompt(context);this.hard=hardRules(context);
  this.stt=providers.stt(session.stt_provider_slug);this.llm=providers.llm(session.llm_provider_slug);this.tts=providers.tts(session.tts_provider_slug);
 }
 async patch(patch,immediate=false){Object.assign(this.sessionPatch,patch,{last_activity_at:new Date().toISOString()});if(immediate)return this.flushPatch();if(!this.patchTimer)this.patchTimer=setTimeout(()=>this.flushPatch().catch(()=>{}),150)}
 async flushPatch(){clearTimeout(this.patchTimer);this.patchTimer=null;const patch=this.sessionPatch;this.sessionPatch={};if(!Object.keys(patch).length)return;await this.admin.from('ai_voice_sessions').update(patch).eq('id',this.session.id)}
 async event(type,payload={}){await this.admin.from('ai_call_events').insert({attempt_id:this.session.attempt_id,event_type:type,event_source:'voice_worker',payload})}
 async transcript(speaker,text,{startMs=0,endMs=null,confidence=null,providerSlug=null,providerSegmentId=null,metadata={}}={}){if(!String(text||'').trim())return null;const {data,error}=await this.admin.rpc('ai_append_transcript_segment',{p_attempt_id:this.session.attempt_id,p_speaker:speaker,p_start_ms:Math.max(0,startMs|0),p_end_ms:endMs==null?null:Math.max(0,endMs|0),p_text:String(text),p_confidence:confidence,p_provider_slug:providerSlug,p_provider_segment_id:providerSegmentId,p_metadata:metadata});if(error)throw error;return data}
 async start(){
  if(this.closed)throw new Error('session closed');
  await this.patch({status:'connecting',provider_states:{stt:'connecting',llm:'ready',tts:'connecting'}},true);
  await Promise.all([
   this.stt.connect({onState:s=>this.patch({provider_states:{...(this.session.provider_states||{}),stt:s}}),onSpeechStarted:e=>this.onSpeechStarted(e),onInterim:e=>this.onInterim(e),onFinal:e=>this.onFinal(e),onUtteranceEnd:()=>this.onUtteranceEnd(),onError:e=>this.providerFailure('stt',e),onClose:e=>{if(!this.closed)this.providerFailure('stt',Object.assign(new Error('STT disconnected'),{code:'STT_DISCONNECT',detail:e}))}}),
   this.tts.connect({onState:s=>this.patch({tts_state:s==='clearing'?'clearing':this.current?.ttsStarted?'speaking':'idle'}),onAudio:b=>this.onTtsAudio(b),onFirstAudio:m=>this.onFirstAudio(m),onFlushed:()=>this.onTtsFlushed(),onError:e=>this.providerFailure('tts',e),onClose:e=>{if(!this.closed)this.providerFailure('tts',Object.assign(new Error('TTS disconnected'),{code:'TTS_DISCONNECT',detail:e}))}})
  ]);
  await this.patch({status:'listening',connected_at:new Date().toISOString(),provider_states:{stt:'connected',llm:'ready',tts:'connected'}},true);await this.event('voice.session.connected',{sessionId:this.session.id,providers:{stt:this.session.stt_provider_slug,llm:this.session.llm_provider_slug,tts:this.session.tts_provider_slug}});
  this.sessionTimeout=setTimeout(()=>this.fail('session',Object.assign(new Error('Maximum controlled voice session duration reached.'),{code:'SESSION_TIMEOUT'})),this.maxSessionMs);
  await this.generateAgentTurn('The phone call has just connected. Give the configured opening greeting now. Do not claim the prospect said anything yet.',{opening:true});
 }
 onMedia(evt){if(this.closed)return;const m=this.transport.ingest(evt);if(m.duplicate||m.ignored)return;if(m.speechDetected&&this.current?.ttsStarted)this.interrupt('audio_vad');if(m.audio)this.stt.sendAudio(m.audio);if(this.now()-this.startedAt>this.maxSessionMs)this.fail('session',Object.assign(new Error('Session timeout.'),{code:'SESSION_TIMEOUT'}))}
 async onSpeechStarted(){if(this.current?.ttsStarted)await this.interrupt('stt_speech_started')}
 async onInterim(e){if(this.closed)return;await this.patch({interim_transcript:e.text,status:this.current?.ttsStarted?'interrupted':'listening'});if(this.current?.ttsStarted)await this.interrupt('stt_interim')}
 async onFinal(e){if(this.closed)return;this.pendingFinal=[this.pendingFinal,e.text].filter(Boolean).join(' ').trim();this.pendingFinalStart=this.pendingFinalStart??e.startMs;this.pendingFinalEnd=e.endMs;this.pendingConfidence.push(e.confidence);await this.patch({interim_transcript:e.speechFinal?'':this.pendingFinal});if(e.speechFinal)await this.commitProspectTurn(e.providerSegmentId)}
 async onUtteranceEnd(){if(this.pendingFinal.trim())await this.commitProspectTurn(null)}
 async commitProspectTurn(providerSegmentId){const text=this.pendingFinal.trim();if(!text)return;const startMs=this.pendingFinalStart??Math.max(0,this.now()-this.startedAt);const endMs=this.pendingFinalEnd??Math.max(startMs,this.now()-this.startedAt);const vals=this.pendingConfidence.filter(Number.isFinite);const confidence=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null;this.pendingFinal='';this.pendingFinalStart=null;this.pendingFinalEnd=null;this.pendingConfidence=[];
  if(this.current)await this.interrupt('new_final_turn');
  const last=this.history[this.history.length-1];if(last?.role==='user'&&last.content===text)return;
  await this.transcript('prospect',text,{startMs,endMs,confidence,providerSlug:this.stt.slug,providerSegmentId,metadata:{phase:7}});this.history.push({role:'user',content:text});this.history=historyTrim(this.history);await this.patch({interim_transcript:'',last_prospect_utterance:text,status:'thinking'});await this.generateAgentTurn(text,{userAlreadyInHistory:true,userFinalAt:this.now()})
 }
 async interrupt(reason){const c=this.current;if(!c||c.interrupted)return;this.generationEpoch++;c.interrupted=true;c.abort.abort(reason);try{this.tts.clear()}catch{};try{this.transport.clear()}catch{};if(c.sentText.trim()&&!c.persisted){await this.transcript('agent',c.sentText.trim(),{startMs:c.agentStartMs,endMs:Math.max(c.agentStartMs,this.now()-this.startedAt),providerSlug:this.tts.slug,metadata:{phase:7,turn_id:c.turnId,interrupted:true,reason,playback_confirmed:false}});c.persisted=true;this.history.push({role:'assistant',content:c.sentText.trim()});this.history=historyTrim(this.history)}await this.patch({status:'interrupted',tts_state:'cancelled',interruption_count:(this.session.interruption_count||0)+1,last_agent_response:c.sentText.trim(),current_turn_id:null},true);this.session.interruption_count=(this.session.interruption_count||0)+1;await this.event('voice.barge_in',{turnId:c.turnId,reason});this.current=null}
 async generateAgentTurn(userText,{opening=false,userAlreadyInHistory=false,userFinalAt=this.now(),repairReason=null}={}){
  if(this.closed)return;if(this.turnNo>=this.maxTurns)return this.fail('session',Object.assign(new Error('Turn limit reached.'),{code:'TURN_LIMIT'}));this.turnNo+=1;const turnId=`${this.session.id}:${this.turnNo}:${crypto.randomUUID().slice(0,8)}`;const epoch=++this.generationEpoch;const abort=new AbortController();const c={turnId,epoch,abort,interrupted:false,ttsStarted:false,ttsFlushed:false,sentText:'',buffer:'',agentStartMs:Math.max(0,this.now()-this.startedAt),userFinalAt,firstTokenLatencyMs:null,ttsFirstAudioLatencyMs:null,persisted:false,repairCount:repairReason?1:0};this.current=c;
  await this.patch({turn_no:this.turnNo,current_turn_id:turnId,status:'thinking',tts_state:'idle'},true);await this.event('voice.turn.started',{turnId,turnNo:this.turnNo,opening});
  const llmHistory=historyTrim(userAlreadyInHistory?this.history.slice(0,-1):this.history);let prompt=userText;if(repairReason)prompt=`${userText}\n\nCOMPLIANCE CORRECTION: The previous draft was blocked. Produce a new short answer that avoids these violations: ${repairReason}. Use only verified knowledge.`;
  try{
   for await(const token of this.llm.streamResponse({system:this.system,history:llmHistory,user:prompt,signal:abort.signal})){
    if(this.closed||epoch!==this.generationEpoch||c.interrupted)return;if(c.firstTokenLatencyMs==null&&token.firstTokenLatencyMs!=null){c.firstTokenLatencyMs=token.firstTokenLatencyMs;await this.recordLatency(turnId,{llm_first_token_ms:c.firstTokenLatencyMs})}c.buffer+=token.delta;if(c.buffer.length+c.sentText.length>900)c.buffer=c.buffer.slice(0,Math.max(0,900-c.sentText.length));const split=splitSpeakable(c.buffer,false);c.buffer=split.rest;for(const chunk of split.chunks){const ok=await this.validateAndSpeak(c,chunk,userText);if(!ok)return}}
   if(this.closed||epoch!==this.generationEpoch||c.interrupted)return;const split=splitSpeakable(c.buffer,true);c.buffer='';for(const chunk of split.chunks){const ok=await this.validateAndSpeak(c,chunk,userText);if(!ok)return}if(!c.sentText.trim()){await this.complianceRepair(c,userText,'empty_or_blocked_response');return}this.tts.flush();c.ttsFlushed=true;await this.patch({last_agent_response:c.sentText.trim(),tts_state:'speaking'});
  }catch(e){if(e?.name==='AbortError'||c.interrupted||epoch!==this.generationEpoch)return;await this.providerFailure('llm',e)}
 }
 async validateAndSpeak(c,chunk,userText){if(!chunk.trim())return true;const verdict=await this.llm.validate({candidate:chunk,hardRules:this.hard,knowledge:this.context.knowledge,signal:c.abort.signal});if(c.epoch!==this.generationEpoch||c.interrupted)return false;if(!verdict.allowed){await this.patch({compliance_state:{blocked:true,turn_id:c.turnId,violations:verdict.violations,unsupported_claims:verdict.unsupportedClaims}});await this.event('voice.compliance.blocked',{turnId:c.turnId,violations:verdict.violations,unsupportedClaims:verdict.unsupportedClaims});await this.complianceRepair(c,userText,[...verdict.violations,...verdict.unsupportedClaims].join('; '));return false}c.sentText+=(c.sentText?' ':'')+chunk.trim();c.ttsStarted=true;this.tts.speak(chunk.trim()+' ');await this.patch({status:'speaking',tts_state:'buffering',compliance_state:{blocked:false,turn_id:c.turnId}});return true}
 async complianceRepair(c,userText,reason){if(c.interrupted)return;c.abort.abort('compliance_regenerate');try{this.tts.clear()}catch{};try{this.transport.clear()}catch{};this.current=null;if(c.repairCount>=1){await this.safeFallback('I do not have enough verified information to answer that safely.');return}await this.generateAgentTurn(userText,{repairReason:String(reason||'compliance_block').slice(0,500),userAlreadyInHistory:true,userFinalAt:c.userFinalAt})}
 async safeFallback(text){if(this.closed)return;const turnId=`${this.session.id}:fallback:${crypto.randomUUID().slice(0,8)}`;const c={turnId,abort:new AbortController(),interrupted:false,ttsStarted:true,ttsFlushed:true,sentText:text,agentStartMs:Math.max(0,this.now()-this.startedAt),persisted:false,userFinalAt:this.now()};this.current=c;this.tts.speak(text);this.tts.flush();await this.patch({status:'speaking',tts_state:'speaking',last_agent_response:text})}
 onTtsAudio(buffer){const c=this.current;if(!c||c.interrupted||this.closed)return;this.transport.sendAudio(buffer,c.turnId);this.patch({status:'speaking',tts_state:'speaking'})}
 async onFirstAudio({latencyMs}){const c=this.current;if(!c)return;c.ttsFirstAudioLatencyMs=latencyMs;const total=Math.max(0,this.now()-c.userFinalAt);await this.recordLatency(c.turnId,{tts_first_audio_ms:latencyMs,total_turn_ms:total})}
 onTtsFlushed(){const c=this.current;if(!c||c.interrupted)return;this.transport.mark(c.turnId)}
 async onMark(evt){const mark=this.transport.acknowledgeMark(evt);if(!mark)return;const c=this.current;if(!c||mark.turnId!==c.turnId||c.interrupted)return;if(c.sentText.trim()&&!c.persisted){await this.transcript('agent',c.sentText.trim(),{startMs:c.agentStartMs,endMs:Math.max(c.agentStartMs,this.now()-this.startedAt),providerSlug:this.tts.slug,metadata:{phase:7,turn_id:c.turnId,interrupted:false,playback_confirmed:true}});c.persisted=true;this.history.push({role:'assistant',content:c.sentText.trim()});this.history=historyTrim(this.history)}await this.patch({status:'listening',tts_state:'idle',last_agent_response:c.sentText.trim(),current_turn_id:null},true);await this.event('voice.turn.completed',{turnId:c.turnId,turnNo:this.turnNo});this.current=null}
 async recordLatency(turnId,values){const current=this.session.latency_metrics||{};const next={...current,[turnId]:{...(current[turnId]||{}),...values,at:new Date().toISOString()}};const keys=Object.keys(next);while(keys.length>30)delete next[keys.shift()];this.session.latency_metrics=next;await this.patch({latency_metrics:next})}
 async providerFailure(kind,e){if(this.closed)return;const err=compactError(e);const errors=[...(this.session.provider_errors||[]),{provider:kind,...err}].slice(-20);this.session.provider_errors=errors;await this.patch({provider_errors:errors,provider_states:{...(this.session.provider_states||{}),[kind]:'failed'}},true);await this.event(`voice.${kind}.failed`,err);await this.fail(kind,e)}
 async fail(kind,e){if(this.closed)return;const err=compactError(e);await this.patch({status:'failed',tts_state:kind==='tts'?'failed':'idle',provider_errors:[...(this.session.provider_errors||[]),{provider:kind,...err}].slice(-20),ended_at:new Date().toISOString()},true);await this.event('voice.session.failed',{provider:kind,...err});this.close('failed')}
 async stop(reason='stream_stop'){if(this.closed)return;await this.patch({status:'completed',tts_state:'idle',ended_at:new Date().toISOString(),current_turn_id:null},true);await this.event('voice.session.completed',{reason,turns:this.turnNo});this.close('completed')}
 close(){if(this.closed)return;this.closed=true;clearTimeout(this.sessionTimeout);clearTimeout(this.patchTimer);try{this.current?.abort?.abort('session_close')}catch{};try{this.stt.close()}catch{};try{this.tts.close()}catch{};try{this.transport.close()}catch{};try{this.socket?.close?.()}catch{}}
}
