import React,{useMemo,useState}from'react';
import{RefreshCw,PlayCircle,Search,CheckCircle2,XCircle}from'lucide-react';
import{supabase}from'./supabaseClient';

const labels={eligible:'Eligible',campaign_not_found:'Campaign not found',campaign_disabled:'Campaign disabled',campaign_not_active:'Campaign not active',prospect_not_found:'Prospect not found',not_stats_prospect:'Not a Cold Call prospect',prospect_deleted:'Prospect deleted',terminal_status:'Terminal Cold Call status',phone_missing:'Phone missing',phone_invalid_or_ambiguous:'Phone invalid or ambiguous',suppressed_or_dnc:'Suppressed / DNC',callback_scheduled:'Callback scheduled',timezone_unresolved:'Timezone unresolved',calling_day_not_allowed:'Calling day not allowed',outside_calling_window:'Outside calling window',attempt_limit_reached:'Attempt limit reached',retry_cooldown:'Retry cooldown',prospect_already_queued_or_active:'Prospect already queued/active',phone_already_active:'Same phone already active',concurrency_limit_reached:'Concurrency limit reached',daily_call_limit_reached:'Daily call limit reached',daily_connected_minutes_limit_reached:'Connected-minutes limit reached',campaign_call_limit_reached:'Campaign call limit reached',daily_spend_limit_reached:'Daily spend limit reached',campaign_spend_limit_reached:'Campaign spend limit reached',duplicate_race_prevented:'Duplicate race prevented'};

async function callApi(body){const{data:{session}}=await supabase.auth.getSession();const res=await fetch('/api/ai-eligibility',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`},body:JSON.stringify(body)});const json=await res.json();if(!res.ok)throw new Error(json.error||'Eligibility request failed');return json}

export default function AIEligibilityPanel({campaigns=[]}){
 const[campaignId,setCampaignId]=useState(campaigns[0]?.id||'');const[preview,setPreview]=useState(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[search,setSearch]=useState('');const[queueLimit,setQueueLimit]=useState(100);const[notice,setNotice]=useState('');
 const rows=useMemo(()=>{const q=search.toLowerCase();return(preview?.rows||[]).filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q))},[preview,search]);
 const runPreview=async()=>{if(!campaignId)return;setLoading(true);setError('');setNotice('');try{setPreview(await callApi({action:'preview',campaignId,limit:10000}))}catch(e){setError(e.message)}setLoading(false)};
 const populate=async()=>{if(!campaignId)return;if(!confirm(`Queue up to ${queueLimit} eligible prospects? This creates call-attempt rows but still places no phone calls.`))return;setLoading(true);setError('');try{const out=await callApi({action:'populate',campaignId,limit:Number(queueLimit)||100});setNotice(`${out.queued} prospects queued. Telephony is still disconnected.`);await runPreview()}catch(e){setError(e.message);setLoading(false)}};
 return <div className="eligibilityPanel"><div className="aiHardBanner"><div><strong>Server-authoritative eligibility</strong><span>The browser only displays results. The database re-checks every prospect before queue insertion.</span></div></div><div className="aiToolbar"><h2>Eligibility & Queue</h2><select value={campaignId} onChange={e=>{setCampaignId(e.target.value);setPreview(null)}}><option value="">Choose campaign</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button onClick={runPreview} disabled={loading||!campaignId}><RefreshCw size={16}/>Dry-run preview</button></div>{error&&<div className="aiAlert error">{error}</div>}{notice&&<div className="aiAlert success">{notice}</div>}{loading&&<div className="aiLoading">Evaluating prospects…</div>}{preview&&<><div className="statsGrid"><div className="stat"><span>Total previewed</span><strong>{preview.total}</strong></div><div className="stat"><span>Eligible</span><strong>{preview.eligible}</strong></div><div className="stat"><span>Ineligible</span><strong>{preview.ineligible}</strong></div></div><div className="aiCards">{Object.entries(preview.reasons||{}).sort((a,b)=>b[1]-a[1]).map(([code,count])=><div className="aiCard" key={code}><div className="aiCardHead"><h3>{labels[code]||code}</h3><span className={code==='eligible'?'pill verified':'pill'}>{count}</span></div><small>{code}</small></div>)}</div><div className="aiToolbar"><div className="aiSearch"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filter by lead ID or reason…"/></div><input type="number" min="1" max="1000" value={queueLimit} onChange={e=>setQueueLimit(e.target.value)} style={{width:110}}/><button className="primary" onClick={populate} disabled={loading||preview.eligible===0}><PlayCircle size={16}/>Queue eligible</button></div><div className="tableWrap"><table><thead><tr><th>Status</th><th>Prospect</th><th>Reason</th><th>Timezone</th><th>Phone</th></tr></thead><tbody>{rows.slice(0,1000).map(r=><tr key={r.prospect_record_id}><td>{r.eligible?<CheckCircle2 size={16}/>:<XCircle size={16}/>}</td><td>{r.prospect_record_id}</td><td><code>{r.reason_code}</code></td><td>{r.details?.lead_timezone||'-'}</td><td>{r.details?.phone_e164||'-'}</td></tr>)}</tbody></table></div></>}</div>
}
