import React,{useEffect,useMemo,useRef,useState}from'react';
import{PhoneCall,RefreshCw,Square,ShieldAlert}from'lucide-react';
import{supabase}from'./supabaseClient';

async function api(path,options={}){const{data:{session}}=await supabase.auth.getSession();const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`,...options.headers}});const j=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(j.reason?`${j.error||'Request failed'} (${j.reason})`:j.error||'Request failed');e.payload=j;throw e}return j}
const terminal=new Set(['completed','busy','no_answer','provider_failed','provider_rejected','provider_auth_error','provider_network_error','cancelled','invalid_number']);
const voiceTerminal=new Set(['completed','failed']);
function latencyRows(metrics={}){return Object.entries(metrics).slice(-8).reverse()}
function fmtLocal(v){if(!v)return'-';return String(v).replace('T',' ').slice(0,19)}

export default function ControlledTestCall({campaigns=[]}){
 const[status,setStatus]=useState(null),[campaignId,setCampaignId]=useState(''),[destination,setDestination]=useState(''),[confirmed,setConfirmed]=useState(false),[attempt,setAttempt]=useState(null),[events,setEvents]=useState([]),[voice,setVoice]=useState(null),[transcript,setTranscript]=useState([]),[diagnostics,setDiagnostics]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const requestKey=useRef(null),placeGuard=useRef(false);
 useEffect(()=>{if(!campaignId){const c=campaigns.find(x=>x.telephony_provider_slug==='twilio');if(c)setCampaignId(c.id)}},[campaigns,campaignId]);
 useEffect(()=>{requestKey.current=null;setConfirmed(false);setDiagnostics(null)},[campaignId,destination]);
 const loadStatus=async()=>{setError('');try{setStatus(await api('/api/ai-controlled-test-call'))}catch(e){setError(e.message)}};
 const diagnose=async(silent=false)=>{if(!campaignId||!destination)return;try{const x=await api('/api/ai-controlled-test-call',{method:'POST',body:JSON.stringify({action:'diagnose',campaignId,destination})});setDiagnostics(x.diagnostics||null);if(!silent)setError('')}catch(e){if(e.payload?.eligibility)setDiagnostics({...e.payload.eligibility,reason_code:e.payload.reason});if(!silent)setError(e.message)}};
 const refresh=async(silent=false)=>{const id=attempt?.id||attempt?.attemptId;if(!id)return;try{const x=await api(`/api/ai-telephony-attempt?attemptId=${id}`);setAttempt(x.attempt);setEvents(x.events||[]);setVoice(x.voiceSession||null);setTranscript(x.transcript||[])}catch(e){if(!silent)setError(e.message)}};
 useEffect(()=>{loadStatus()},[]);
 useEffect(()=>{if(!attempt?.id||terminal.has(attempt.status)||voiceTerminal.has(voice?.status))return;const t=setInterval(()=>refresh(true),1200);return()=>clearInterval(t)},[attempt?.id,attempt?.status,voice?.status]);
 const place=async()=>{if(!confirmed||placeGuard.current)return;placeGuard.current=true;setBusy(true);setError('');if(!requestKey.current)requestKey.current=crypto.randomUUID().replaceAll('-','');try{const x=await api('/api/ai-controlled-test-call',{method:'POST',body:JSON.stringify({action:'place',campaignId,destination,requestKey:requestKey.current,confirmation:'PLACE ONE REAL TWILIO CALL'})});setAttempt({id:x.attemptId,provider_call_id:x.callSid,status:x.state,provider_status:x.providerStatus});setVoice(x.voiceSessionId?{id:x.voiceSessionId,status:'connecting'}:null);setConfirmed(false);if(x.originationUncertain)setError('Twilio origination may have started but the Call SID is not yet persisted. Do not retry with a new request key. Refresh this attempt first.')}catch(e){if(e.payload?.eligibility)setDiagnostics(d=>({...d,...e.payload.eligibility,reason_code:e.payload.reason||e.payload.eligibility.reason_code}));setError(e.message)}finally{setBusy(false);placeGuard.current=false}};
 const terminate=async()=>{if(!attempt?.id)return;setBusy(true);setError('');try{await api('/api/ai-controlled-test-call',{method:'POST',body:JSON.stringify({action:'terminate',attemptId:attempt.id})});await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const reconcile=async()=>{if(!attempt?.id)return;setBusy(true);setError('');try{const x=await api('/api/ai-telephony-attempt',{method:'POST',body:JSON.stringify({action:'reconcileCost',attemptId:attempt.id})});setAttempt(x.attempt);await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const prepareAnother=()=>{if(attempt&&!terminal.has(attempt.status)){setError('The current controlled attempt is not terminal yet. Terminate or finish it before preparing another test.');return}requestKey.current=null;setAttempt(null);setEvents([]);setVoice(null);setTranscript([]);setDiagnostics(null);setConfirmed(false);setError('')};
 const selected=campaigns.find(c=>c.id===campaignId);const twilioCampaigns=campaigns.filter(c=>c.telephony_provider_slug==='twilio');const providerReady=Boolean(selected?.stt_provider_slug&&selected?.llm_provider_slug&&selected?.tts_provider_slug);const latestLatency=useMemo(()=>latencyRows(voice?.latency_metrics||{}),[voice?.latency_metrics]);
 return <div className="eligibilityPanel">
  <div className="aiHardBanner"><ShieldAlert size={20}/><div><strong>This places one real conversational phone call through Twilio.</strong><span>Phase 7 keeps the Phase 6 controlled-test boundary. Bulk dialing, campaign queue consumption, dialing loops and automatic call retries remain disabled.</span></div></div>
  <div className="aiToolbar"><h2>Controlled Conversational Test</h2><button onClick={loadStatus}><RefreshCw size={16}/>Configuration</button></div>
  {error&&<div className="aiAlert error">{error}</div>}
  {status&&<div className="aiCards"><div className="aiCard"><h3>Controlled voice stack</h3><div className="aiMeta"><span>Twilio: {status.configured?'Configured':'Missing'}</span><span>Media WebSocket: {status.voiceMediaConfigured?'Configured':'Missing'}</span><span>From: {status.fromNumber||'Missing'}</span><span>Webhook: {status.webhookConfigured?'Configured':'Missing'}</span><span>Controlled test: {status.controlledTestEnabled?'ENABLED':'SERVER LOCKED'}</span><span>Bulk dialing: Disabled</span><span>Autonomous queue: Disabled</span></div>{status.configurationError&&<p>{status.configurationError}</p>}</div></div>}
  <div className="gridForm">
   <label className="aiField"><span>Twilio campaign</span><select value={campaignId} onChange={e=>setCampaignId(e.target.value)}><option value="">Choose campaign</option>{twilioCampaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
   <label className="aiField"><span>Destination (international E.164 only)</span><input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="+32…"/></label>
   {selected&&<div className="aiField aiWide"><span>Conversation providers</span><div className="aiMeta"><span>STT: {selected.stt_provider_slug||'Missing'}</span><span>LLM: {selected.llm_provider_slug||'Missing'}</span><span>TTS: {selected.tts_provider_slug||'Missing'}</span></div>{!providerReady&&<small>This campaign is not ready for Phase 7 until all three provider slugs are selected.</small>}</div>}
   <label className="aiField aiWide"><span><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I understand that pressing the button below places ONE REAL PHONE CALL and starts the real-time AI voice pipeline.</span></label>
  </div>
  <div className="aiActions"><button disabled={busy||!campaignId||!destination} onClick={()=>diagnose(false)}><RefreshCw size={14}/>Check eligibility</button><button className="primary" disabled={busy||!confirmed||!campaignId||!destination||!providerReady||!status?.readyForTest||!status?.controlledTestEnabled||diagnostics?.eligible===false} onClick={place}><PhoneCall size={16}/>Place Controlled Conversational Call</button>{attempt?.provider_call_id&&!terminal.has(attempt.status)&&<button className="danger" disabled={busy} onClick={terminate}><Square size={14}/>Terminate Call</button>}<button disabled={busy||!attempt?.id} onClick={()=>refresh(false)}>Refresh live state</button><button disabled={busy||!attempt?.provider_call_id||attempt?.cost_status==='reconciled'} onClick={reconcile}>Reconcile cost</button><button disabled={busy||!attempt} onClick={prepareAnother}>Prepare another test</button></div>
  {diagnostics&&<div className="aiCards"><div className="aiCard"><h3>Eligibility diagnostics</h3><div className="aiMeta"><span>Eligibility: {diagnostics.eligible?'ELIGIBLE':'BLOCKED'}</span><span>Reason: {diagnostics.reason_code||'-'}</span><span>Lead timezone: {diagnostics.lead_timezone||'-'}</span><span>Lead-local time: {fmtLocal(diagnostics.lead_local_time||diagnostics.local_time)}</span><span>Calling window: {String(diagnostics.calling_window_start||selected?.calling_window_start||'-').slice(0,5)}–{String(diagnostics.calling_window_end||selected?.calling_window_end||'-').slice(0,5)}</span><span>Calling days: {(diagnostics.calling_days||selected?.calling_days||[]).join(', ')||'-'}</span><span>Normal attempts: {diagnostics.normal_attempts??diagnostics.eligibility?.normal_attempts??'-'} / {diagnostics.max_attempts??selected?.max_attempts_per_prospect??'-'}</span><span>Controlled tests: {diagnostics.controlled_attempts??'-'}</span><span>Total attempts: {diagnostics.total_attempts??diagnostics.eligibility?.total_calls??'-'}</span><span>Retry after: {diagnostics.retry_after||'now / none'}</span><span>Active campaign calls: {diagnostics.active_campaign_calls??diagnostics.eligibility?.active_calls??'-'}</span><span>Lead queued/active: {diagnostics.active_or_queued_for_prospect??'-'}</span></div></div></div>}
  {attempt&&<><div className="aiCards"><div className="aiCard"><h3>Telephony attempt</h3><div className="aiMeta"><span>Attempt: {attempt.id}</span><span>Twilio SID: {attempt.provider_call_id||'-'}</span><span>Internal: {attempt.status}</span><span>Twilio: {attempt.provider_status||'-'}</span><span>Connected: {attempt.connected_seconds??'-'} sec</span><span>Total: {attempt.duration_seconds??'-'} sec</span><span>Cost: {attempt.cost_status||'pending'} {attempt.actual_cost!=null?`${attempt.actual_cost} ${attempt.cost_currency}`:''}</span><span>Error: {attempt.failure_reason||'-'}</span></div></div>
   <div className="aiCard"><h3>Live conversation</h3>{voice?<div className="aiMeta"><span>Session: {voice.status}</span><span>Stream: {voice.stream_sid?'Connected':'Waiting'}</span><span>STT: {voice.stt_provider_slug||'-'} · {voice.provider_states?.stt||'-'}</span><span>LLM: {voice.llm_provider_slug||'-'} · {voice.provider_states?.llm||'-'}</span><span>TTS: {voice.tts_provider_slug||'-'} · {voice.tts_state||'-'}</span><span>Turn: {voice.turn_no??0}</span><span>Interruptions: {voice.interruption_count??0}</span><span>Compliance: {voice.compliance_state?.blocked?'BLOCKED / REGENERATING':'Clear'}</span><span>Last prospect: {voice.last_prospect_utterance||'-'}</span><span>Last agent: {voice.last_agent_response||'-'}</span><span>Live interim: {voice.interim_transcript||'-'}</span></div>:<p>Voice session has not connected yet.</p>}{voice?.provider_errors?.length>0&&<div className="aiAlert error">Latest provider error: {voice.provider_errors.at(-1)?.provider} — {voice.provider_errors.at(-1)?.message}</div>}</div></div>
   {latestLatency.length>0&&<div className="tableWrap"><table><thead><tr><th>Turn</th><th>STT final</th><th>LLM first token</th><th>TTS first audio</th><th>Total turn</th></tr></thead><tbody>{latestLatency.map(([id,m])=><tr key={id}><td>{id}</td><td>{m.stt_final_ms??'-'} ms</td><td>{m.llm_first_token_ms??'-'} ms</td><td>{m.tts_first_audio_ms??'-'} ms</td><td>{m.total_turn_ms??'-'} ms</td></tr>)}</tbody></table></div>}
   <div className="tableWrap"><table><thead><tr><th>#</th><th>Speaker</th><th>Final transcript</th><th>Confidence</th></tr></thead><tbody>{transcript.length?transcript.map(s=><tr key={s.id}><td>{s.sequence_no}</td><td>{s.speaker}</td><td>{s.text}</td><td>{s.confidence==null?'-':Number(s.confidence).toFixed(2)}</td></tr>):<tr><td colSpan="4">No final transcript segments yet.</td></tr>}</tbody></table></div>
   <div className="tableWrap"><table><thead><tr><th>Time</th><th>Lifecycle / voice event</th><th>Source</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{e.occurred_at}</td><td>{e.event_type}</td><td>{e.event_source}</td></tr>)}</tbody></table></div></>}
 </div>;
}
