import React,{useEffect,useRef,useState}from'react';
import{PhoneCall,RefreshCw,Square,ShieldAlert}from'lucide-react';
import{supabase}from'./supabaseClient';

async function api(path,options={}){const{data:{session}}=await supabase.auth.getSession();const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`,...options.headers}});const j=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(j.reason?`${j.error||'Request failed'} (${j.reason})`:j.error||'Request failed');e.payload=j;throw e}return j}
const terminal=new Set(['completed','busy','no_answer','provider_failed','provider_rejected','provider_auth_error','provider_network_error','cancelled','invalid_number']);

export default function ControlledTestCall({campaigns=[]}){
 const[status,setStatus]=useState(null),[campaignId,setCampaignId]=useState(''),[destination,setDestination]=useState(''),[confirmed,setConfirmed]=useState(false),[attempt,setAttempt]=useState(null),[events,setEvents]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const requestKey=useRef(null),placeGuard=useRef(false);
 useEffect(()=>{if(!campaignId){const twilioCampaign=campaigns.find(c=>c.telephony_provider_slug==='twilio');if(twilioCampaign)setCampaignId(twilioCampaign.id)}},[campaigns,campaignId]);
 useEffect(()=>{requestKey.current=null;setConfirmed(false)},[campaignId,destination]);
 const loadStatus=async()=>{setError('');try{setStatus(await api('/api/ai-controlled-test-call'))}catch(e){setError(e.message)}};
 const refresh=async()=>{const id=attempt?.id||attempt?.attemptId;if(!id)return;try{const x=await api(`/api/ai-telephony-attempt?attemptId=${id}`);setAttempt(x.attempt);setEvents(x.events||[])}catch(e){setError(e.message)}};
 useEffect(()=>{loadStatus()},[]);
 const place=async()=>{if(!confirmed||placeGuard.current)return;placeGuard.current=true;setBusy(true);setError('');if(!requestKey.current)requestKey.current=crypto.randomUUID().replaceAll('-','');try{const x=await api('/api/ai-controlled-test-call',{method:'POST',body:JSON.stringify({action:'place',campaignId,destination,requestKey:requestKey.current,confirmation:'PLACE ONE REAL TWILIO CALL'})});setAttempt({id:x.attemptId,provider_call_id:x.callSid,status:x.state,provider_status:x.providerStatus});setConfirmed(false);if(x.originationUncertain)setError('Twilio origination may have started but the Call SID is not yet persisted. Do not retry with a new request key. Refresh this attempt first.')}catch(e){setError(e.message)}finally{setBusy(false);placeGuard.current=false}};
 const terminate=async()=>{if(!attempt?.id)return;setBusy(true);setError('');try{await api('/api/ai-controlled-test-call',{method:'POST',body:JSON.stringify({action:'terminate',attemptId:attempt.id})});await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const reconcile=async()=>{if(!attempt?.id)return;setBusy(true);setError('');try{const x=await api('/api/ai-telephony-attempt',{method:'POST',body:JSON.stringify({action:'reconcileCost',attemptId:attempt.id})});setAttempt(x.attempt);await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const prepareAnother=()=>{if(attempt&&!terminal.has(attempt.status)){setError('The current controlled attempt is not terminal yet. Terminate or finish it before preparing another test.');return}requestKey.current=null;setAttempt(null);setEvents([]);setConfirmed(false);setError('')};
 const twilioCampaigns=campaigns.filter(c=>c.telephony_provider_slug==='twilio');
 return <div className="eligibilityPanel">
  <div className="aiHardBanner"><ShieldAlert size={20}/><div><strong>This places a real phone call through Twilio.</strong><span>Phase 6 permits one deliberately initiated controlled call only. Production campaign queue consumption, dialing loops and automatic call retries are disabled.</span></div></div>
  <div className="aiToolbar"><h2>Controlled Test Call</h2><button onClick={loadStatus}><RefreshCw size={16}/>Configuration</button></div>
  {error&&<div className="aiAlert error">{error}</div>}
  {status&&<div className="aiCards"><div className="aiCard"><h3>Provider: Twilio</h3><div className="aiMeta"><span>Configured: {status.configured?'Yes':'No'}</span><span>From number: {status.fromNumber||'Missing'}</span><span>Webhook: {status.webhookConfigured?'Configured':'Missing'}</span><span>Controlled test: {status.controlledTestEnabled?'ENABLED':'SERVER LOCKED'}</span><span>Bulk dialing: Disabled</span></div>{status.configurationError&&<p>{status.configurationError}</p>}</div></div>}
  <div className="gridForm">
   <label className="aiField"><span>Twilio campaign</span><select value={campaignId} onChange={e=>setCampaignId(e.target.value)}><option value="">Choose campaign</option>{twilioCampaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
   <label className="aiField"><span>Destination (international E.164 only)</span><input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="+32…"/></label>
   <label className="aiField aiWide"><span><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I understand that pressing the button below places ONE REAL PHONE CALL through Twilio.</span></label>
  </div>
  <div className="aiActions"><button className="primary" disabled={busy||!confirmed||!campaignId||!destination||!status?.readyForTest||!status?.controlledTestEnabled} onClick={place}><PhoneCall size={16}/>Place Controlled Test Call</button>{attempt?.provider_call_id&&!terminal.has(attempt.status)&&<button className="danger" disabled={busy} onClick={terminate}><Square size={14}/>Terminate Call</button>}<button disabled={busy||!attempt?.id} onClick={refresh}>Refresh lifecycle</button><button disabled={busy||!attempt?.provider_call_id||attempt?.cost_status==='reconciled'} onClick={reconcile}>Reconcile cost</button><button disabled={busy||!attempt} onClick={prepareAnother}>Prepare another test</button></div>
  {attempt&&<><div className="aiCards"><div className="aiCard"><h3>Attempt {attempt.id}</h3><div className="aiMeta"><span>Twilio Call SID: {attempt.provider_call_id||'-'}</span><span>Internal state: {attempt.status}</span><span>Twilio state: {attempt.provider_status||'-'}</span><span>Initiated: {attempt.initiated_at||'-'}</span><span>Ringing: {attempt.ringing_at||'-'}</span><span>Answered: {attempt.answered_at||'-'}</span><span>Completed: {attempt.completed_at||'-'}</span><span>Connected duration: {attempt.connected_seconds??'-'} sec</span><span>Total duration: {attempt.duration_seconds??'-'} sec</span><span>Cost status: {attempt.cost_status||'pending'}</span><span>Actual cost: {attempt.actual_cost!=null?`${attempt.actual_cost} ${attempt.cost_currency}`:'Pending / unavailable'}</span><span>Provider error: {attempt.failure_reason||'-'}</span></div></div></div><div className="tableWrap"><table><thead><tr><th>Time</th><th>Lifecycle event</th><th>Source</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{e.occurred_at}</td><td>{e.event_type}</td><td>{e.event_source}</td></tr>)}</tbody></table></div></>}
 </div>;
}
