import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{Plus,Trash2,Edit,Save,X,Search,Download,Upload,Phone,Users,Briefcase,BarChart3,ClipboardList,Home,LogOut,Lock,ShieldCheck,RefreshCw,History}from'lucide-react';
import{supabase}from'./supabaseClient';
import'./styles.css';

const emptyData={leads:[],clients:[],freelancers:[],submissions:[],stats:[]};
const coldCallStatuses=['dialed','opener','conversation','pitched','interested','callback','booked'];
const logTypes=['leads','submissions','stats'];
const today=()=>new Date().toISOString().slice(0,10);
const tabs=[['dashboard',Home,'Dashboard'],['leads',Phone,'Leads'],['clients',Briefcase,'Clients'],['freelancers',Users,'Freelancers'],['submissions',ClipboardList,'Submissions'],['stats',BarChart3,'Cold Call Stats'],['activity',History,'Activity Log']];
const rolePermissions={admin:{label:'Admin',tabs:['dashboard','leads','clients','freelancers','submissions','stats','activity'],recordTypes:['leads','clients','freelancers','submissions','stats'],canExport:true,canImport:true,canWrite:true,canDelete:true,canViewActivity:true},freelancer:{label:'Freelancer',tabs:['dashboard','leads','submissions','stats'],recordTypes:['leads','submissions','stats'],canExport:false,canImport:false,canWrite:true,canDelete:false,canViewActivity:false}};
function getUserRole(user){const role=String(user?.app_metadata?.role||user?.user_metadata?.role||'').trim().toLowerCase();return rolePermissions[role]?role:null}
function isUuid(v){return/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''))}
function norm(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function parseCsv(text){const lines=String(text||'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const headers=lines[0].split(/[;,\t]/).map(norm);return lines.slice(1).map(line=>{const vals=line.split(/[;,\t]/);const row={};headers.forEach((h,i)=>{if(h)row[h]=vals[i]||''});return row})}
function csvVal(row,aliases){const key=aliases.map(norm).find(a=>row[a]!==undefined&&String(row[a]).trim()!=='');return key?String(row[key]).trim():''}
function normalizeColdCallStatus(v){const s=String(v||'').trim().toLowerCase();return coldCallStatuses.includes(s)?s:''}
function mapCsvRowsToColdCallProspects(rows){const importedAt=today();return rows.map(row=>{const first=csvVal(row,['first name','firstname','voornaam']);const last=csvVal(row,['last name','lastname','achternaam']);const name=csvVal(row,['name','full name','fullname','naam','lead name','contact name','agent name','realtor name','title','persoon','contact'])||[first,last].filter(Boolean).join(' ');return{name,phone:csvVal(row,['phone','phone number','phonenumber','mobile','tel','telephone','gsm','nummer','telefoon','mobiel']),email:csvVal(row,['email','email address','emailaddress','mail','e-mail','e-mailadres','email1']),importedAt,status:normalizeColdCallStatus(csvVal(row,['status','stage','lead status','cold call status'])),notes:csvVal(row,['notes','note','opmerkingen','notities','description','omschrijving'])}}).filter(p=>p.name||p.phone||p.email)}
function mapCsvRowsToType(type,rows){if(type==='stats')return mapCsvRowsToColdCallProspects(rows);const aliases={name:['name','fullname','fullnaam','voornaamachternaam','leadname','contactname'],fullName:['fullname','name','naam','contactname'],company:['company','bedrijf','agency','brokerage','kantoor'],email:['email','emailaddress','mail','e-mailadres'],phone:['phone','phonenumber','tel','telephone','gsm','nummer'],niche:['niche','market','markt'],status:['status','stage'],value:['value','criteria','budget','price','waarde'],notes:['notes','note','opmerkingen','notities','description'],plan:['plan'],monthly:['monthly','retainer','monthlyretainer'],role:['role','functie'],pay:['pay','payment','paystructure','payout'],buyerStatus:['buyerstatus','buyerclients','buyers','areyoucurrentlyworkingwithbuyerclients'],leadSource:['leadsource','source','howareyoucurrentlygeneratingbuyerleads'],openToAppointments:['opentoappointments','appointment','areyouopentoreceivingprequalifiedbuyerappointments'],preferredType:['preferredtype','preferredclienttype','clienttype'],assigned_to_user_id:['assignedtouserid','assigneduser','assignedto','owner','freelanceruserid']};const fields=fieldSets[type]||fieldSets.leads;return rows.map(row=>{const item={};fields.forEach(f=>item[f.key]=csvVal(row,aliases[f.key]||[f.key]));return item})}
function groupRecords(rows,role,userId){const grouped={leads:[],clients:[],freelancers:[],submissions:[],stats:[]};(rows||[]).forEach(row=>{if(!grouped[row.type])return;const payload={...(row.payload||{}),id:row.id};if(payload.deleted)return;payload.assigned_to_user_id=payload.assigned_to_user_id||row.assigned_to_user_id||'';payload.created_by_user_id=payload.created_by_user_id||row.created_by_user_id||'';if(role==='freelancer'&&row.type==='leads'&&payload.assigned_to_user_id!==userId)return;grouped[row.type].push(payload)});return grouped}
function useSupabaseData(role,user){const[data,setData]=useState(emptyData);const[activityLogs,setActivityLogs]=useState([]);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
 const loadActivityLogs=async()=>{if(!rolePermissions[role]?.canViewActivity)return;const{data:rows,error}=await supabase.from('activity_logs').select('*').order('created_at',{ascending:false}).limit(250);if(!error)setActivityLogs(rows||[])};
 const loadData=async()=>{if(!role||!user?.id)return;setLoading(true);setError('');const allowed=rolePermissions[role].recordTypes;const{data:rows,error}=await supabase.from('crm_records').select('id,type,payload,created_at,assigned_to_user_id,created_by_user_id').in('type',allowed).order('created_at',{ascending:false});if(error){setError(error.message);setData(emptyData)}else{setData(groupRecords(rows,role,user.id));await loadActivityLogs()}setLoading(false)};
 useEffect(()=>{loadData()},[role,user?.id]);
 const insertLog=async(log)=>{if(!logTypes.includes(log.record_type))return;const{error:logError}=await supabase.from('activity_logs').insert({id:crypto.randomUUID(),user_id:user.id,user_email:user.email,created_at:new Date().toISOString(),...log});if(logError&&rolePermissions[role]?.canViewActivity)setError(`Record saved, but activity log failed: ${logError.message}`);else await loadActivityLogs()};
 const saveRecord=async(type,item)=>{if(!rolePermissions[role]?.recordTypes.includes(type))return;const existing=data[type]?.find(r=>r.id===item.id);const id=isUuid(item.id)?item.id:crypto.randomUUID();const assignedTo=type==='leads'?(role==='admin'?(item.assigned_to_user_id||''):user.id):(item.assigned_to_user_id||null);const createdBy=item.created_by_user_id||existing?.created_by_user_id||user.id;const payload={...item,id,deleted:false,created:item.created||existing?.created||today(),created_by_user_id:createdBy,assigned_to_user_id:type==='leads'?assignedTo:item.assigned_to_user_id,importedAt:type==='stats'?(item.importedAt||today()):item.importedAt};const visible={...payload,id};setData(prev=>({...prev,[type]:(prev[type]||[]).some(r=>r.id===id)?(prev[type]||[]).map(r=>r.id===id?visible:r):[visible,...(prev[type]||[])]}));const row={id,type,payload,assigned_to_user_id:type==='leads'?(assignedTo||null):null,created_by_user_id:createdBy||null,updated_at:new Date().toISOString()};const{error}=await supabase.from('crm_records').upsert(row);if(error){setError(error.message);return}await insertLog({action:existing?'update':'create',record_type:type,record_id:id,before_payload:existing||null,after_payload:payload})};
 const softDeleteRows=async(type,items)=>{if(!rolePermissions[role]?.canDelete||!rolePermissions[role]?.recordTypes.includes(type)||!items.length)return;setData(prev=>({...prev,[type]:(prev[type]||[]).filter(row=>!items.some(item=>item.id===row.id))}));const deletedAt=new Date().toISOString();const rows=items.map(item=>({id:item.id,type,payload:{...item,deleted:true,deletedAt},assigned_to_user_id:type==='leads'?(item.assigned_to_user_id||null):null,created_by_user_id:item.created_by_user_id||user.id,updated_at:deletedAt}));const{error}=await supabase.from('crm_records').upsert(rows);if(error){setError(error.message);return}const logs=items.filter(item=>logTypes.includes(type)).map(item=>({id:crypto.randomUUID(),user_id:user.id,user_email:user.email,action:'delete',record_type:type,record_id:item.id,before_payload:item,after_payload:{...item,deleted:true,deletedAt},created_at:deletedAt}));if(logs.length){const{error:logError}=await supabase.from('activity_logs').insert(logs);if(logError&&rolePermissions[role]?.canViewActivity)setError(`Deleted, but activity log failed: ${logError.message}`);await loadActivityLogs()}};
 const deleteRecord=async(type,id)=>{const item=data[type]?.find(row=>row.id===id);if(item)await softDeleteRows(type,[item])};
 const deleteAllRecords=async type=>softDeleteRows(type,data[type]||[]);
 const importRecords=async importedData=>{if(!rolePermissions[role]?.canImport)return;const now=new Date().toISOString();const newVisible={};const rows=Object.entries(importedData||{}).flatMap(([type,items])=>{if(!rolePermissions[role].recordTypes.includes(type)||!Array.isArray(items))return[];newVisible[type]=[];return items.map(item=>{const id=isUuid(item.id)?item.id:crypto.randomUUID();const payload={...item,id,deleted:false,created:item.created||today(),created_by_user_id:item.created_by_user_id||user.id,assigned_to_user_id:type==='leads'?(item.assigned_to_user_id||''):item.assigned_to_user_id,importedAt:type==='stats'?(item.importedAt||today()):item.importedAt};newVisible[type].push(payload);return{id,type,payload,assigned_to_user_id:type==='leads'?(payload.assigned_to_user_id||null):null,created_by_user_id:payload.created_by_user_id,updated_at:now}})});if(!rows.length)return;setData(prev=>{const next={...prev};Object.entries(newVisible).forEach(([type,items])=>next[type]=[...items,...(prev[type]||[])]);return next});const{error}=await supabase.from('crm_records').upsert(rows);if(error){setError(error.message);return}const logs=rows.filter(r=>logTypes.includes(r.type)).map(r=>({id:crypto.randomUUID(),user_id:user.id,user_email:user.email,action:'create',record_type:r.type,record_id:r.id,before_payload:null,after_payload:r.payload,created_at:now}));if(logs.length){const{error:logError}=await supabase.from('activity_logs').insert(logs);if(logError)setError(`Import saved, but activity log failed: ${logError.message}`);await loadActivityLogs()}};
 return{data,activityLogs,loading,error,loadData,saveRecord,deleteRecord,deleteAllRecords,importRecords}}
function Empty({text}){return <div className="empty">{text}</div>}
function AccessDenied({session,onLogout}){return <div className="loginPage"><div className="loginCard"><div className="loginLogo"><ShieldCheck size={24}/><strong>AdLift CRM</strong></div><h1>No role assigned</h1><p>This account is logged in, but it does not have an admin or freelancer role yet.</p><div className="authError">Ask the Supabase admin to set <b>role</b> to <b>admin</b> or <b>freelancer</b> in this user's metadata.</div><small>{session.user.email}</small><button className="primary full" onClick={onLogout}><LogOut size={16}/>Logout</button></div></div>}
function Modal({title,fields,initial={},onClose,onSave}){const[form,setForm]=useState(initial);const update=(k,v)=>setForm(prev=>({...prev,[k]:v}));return <div className="overlay"><div className="modal"><div className="modalHead"><h2>{title}</h2><button onClick={onClose}><X size={18}/></button></div><div className="gridForm">{fields.map(f=><label key={f.key}>{f.label}{f.type==='textarea'?<textarea value={form[f.key]||''} onChange={e=>update(f.key,e.target.value)}/>:f.type==='select'?<select value={form[f.key]||''} onChange={e=>update(f.key,e.target.value)}><option value="">Choose status</option>{(f.options||[]).map(o=><option key={o} value={o}>{o}</option>)}</select>:<input type={f.type||'text'} value={form[f.key]||''} onChange={e=>update(f.key,e.target.value)}/>}</label>)}</div><button className="primary full" onClick={()=>onSave({...form,id:form.id||crypto.randomUUID(),created:form.created||today()})}><Save size={16}/> Save</button></div></div>}
const fieldSets={leads:[{key:'name',label:'Client Lead Name'},{key:'company',label:'Client / Company'},{key:'email',label:'Email'},{key:'phone',label:'Phone'},{key:'niche',label:'Niche'},{key:'status',label:'Qualification Status'},{key:'value',label:'Value / Criteria'},{key:'assigned_to_user_id',label:'Assigned Freelancer User ID'},{key:'notes',label:'Notes',type:'textarea'}],clients:[{key:'name',label:'Client Name'},{key:'company',label:'Company'},{key:'email',label:'Email'},{key:'plan',label:'Plan'},{key:'status',label:'Status'},{key:'monthly',label:'Monthly Retainer'},{key:'notes',label:'Notes',type:'textarea'}],freelancers:[{key:'name',label:'Name'},{key:'role',label:'Role'},{key:'email',label:'Email'},{key:'user_id',label:'Supabase User ID'},{key:'pay',label:'Pay Structure'},{key:'status',label:'Status'},{key:'notes',label:'Notes',type:'textarea'}],submissions:[{key:'fullName',label:'Full Name'},{key:'email',label:'Email'},{key:'phone',label:'Phone'},{key:'buyerStatus',label:'Buyer Clients?'},{key:'leadSource',label:'Current Lead Source'},{key:'openToAppointments',label:'Open to Appointments?'},{key:'preferredType',label:'Preferred Client Type'},{key:'notes',label:'Notes',type:'textarea'}],stats:[{key:'name',label:'Prospect Name'},{key:'phone',label:'Phone Number'},{key:'email',label:'Email'},{key:'importedAt',label:'Imported On',type:'date'},{key:'status',label:'Cold Call Status',type:'select',options:coldCallStatuses},{key:'notes',label:'Notes',type:'textarea'}]};
function formatHeader(type,key){return fieldSets[type].find(f=>f.key===key)?.label||key}
function renderCell(type,key,row,permissions,onSave){if(type==='stats'&&key==='status'&&permissions.canWrite)return <select className="tableSelect" value={row.status||''} onChange={e=>onSave(type,{...row,status:e.target.value})}><option value="">Choose status</option>{coldCallStatuses.map(s=><option key={s} value={s}>{s}</option>)}</select>;return String(row[key]||'-')}
function TableSection({type,title,data,permissions,onSave,onDelete,onDeleteAll}){const[search,setSearch]=useState('');const[modal,setModal]=useState(null);const rows=data[type]||[];const filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));const save=async item=>{await onSave(type,item);setModal(null)};const keys=type==='stats'?['name','phone','email','importedAt','status','notes']:type==='leads'?['name','company','email','phone','status','assigned_to_user_id']:fieldSets[type].map(f=>f.key).slice(0,5);const handleDeleteAll=async()=>{if(window.confirm(`Are you sure you want to delete all ${title.toLowerCase()}? This cannot be undone.`))await onDeleteAll(type)};return <section className="card"><div className="sectionTop"><div><h1>{title}</h1><p>{filtered.length} records</p></div><div className="sectionActions">{permissions.canDelete&&rows.length>0&&<button className="danger" onClick={handleDeleteAll}><Trash2 size={16}/> Delete all</button>}{permissions.canWrite&&<button className="primary" onClick={()=>setModal(type==='stats'?{importedAt:today()}: {})}><Plus size={16}/> Add</button>}</div></div><div className="search"><Search size={16}/><input placeholder={`Search ${title.toLowerCase()}...`} value={search} onChange={e=>setSearch(e.target.value)}/></div>{filtered.length===0?<Empty text="No records yet. Add one or import a CSV."/>:<div className="tableWrap"><table><thead><tr>{keys.map(k=><th key={k}>{formatHeader(type,k)}</th>)}{permissions.canWrite&&<th>Actions</th>}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}>{keys.map(k=><td key={k}>{renderCell(type,k,r,permissions,onSave)}</td>)}{permissions.canWrite&&<td className="actions"><button onClick={()=>setModal(r)}><Edit size={15}/></button>{permissions.canDelete&&<button onClick={()=>onDelete(type,r.id)}><Trash2 size={15}/></button>}</td>}</tr>)}</tbody></table></div>}{modal&&permissions.canWrite&&<Modal title={`${modal.id?'Edit':'Add'} ${title}`} fields={fieldSets[type]} initial={modal} onClose={()=>setModal(null)} onSave={save}/>}</section>}
function ActivityLog({logs}){return <section className="card"><div className="sectionTop"><div><h1>Activity Log</h1><p>{logs.length} recent actions</p></div></div>{logs.length===0?<Empty text="No activity logged yet."/>:<div className="tableWrap"><table><thead><tr><th>Time</th><th>User</th><th>Action</th><th>Record Type</th><th>Record ID</th></tr></thead><tbody>{logs.map(log=><tr key={log.id}><td>{new Date(log.created_at).toLocaleString()}</td><td>{log.user_email||log.user_id||'-'}</td><td><span className={`logBadge ${log.action}`}>{log.action}</span></td><td>{log.record_type}</td><td>{log.record_id}</td></tr>)}</tbody></table></div>}</section>}
function Dashboard({data,role}){const prospects=data.stats||[];const interested=prospects.filter(x=>x.status==='interested').length;const booked=prospects.filter(x=>x.status==='booked').length;const callbacks=prospects.filter(x=>x.status==='callback').length;const cards=role==='admin'?[['Client Leads',data.leads.length],['Clients',data.clients.length],['Freelancers',data.freelancers.length],['Cold Call Prospects',prospects.length],['Interested',interested],['Booked',booked]]:[['Assigned Leads',data.leads.length],['Submissions',data.submissions.length],['Cold Call Prospects',prospects.length],['Callbacks',callbacks],['Booked',booked]];return <section className="card"><h1>AdLift Dashboard</h1><p className="sub">Shared CRM data from Supabase.</p><div className="statsGrid">{cards.map(([a,b])=><div className="stat" key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>{role==='admin'&&<><h2>Cold Call Pipeline</h2><div className="pipeline">{coldCallStatuses.map(stage=><div className="pipe" key={stage}><b>{stage}</b><span>{prospects.filter(l=>(l.status||'').toLowerCase()===stage).length}</span></div>)}</div></>}</section>}
function LoginPage(){const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const login=async e=>{e.preventDefault();setLoading(true);setError('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setLoading(false)};return <div className="loginPage"><form className="loginCard" onSubmit={login}><div className="loginLogo"><Lock size={24}/><strong>AdLift CRM</strong></div><h1>Private access</h1><p>Login with the account created in Supabase.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@adlift.com" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" required/></label>{error&&<div className="authError">{error}</div>}<button className="primary full" disabled={loading}>{loading?'Logging in...':'Login'}</button><small>No public sign-up. Create users from Supabase → Authentication → Users.</small></form></div>}
function App(){const[session,setSession]=useState(null);const[authLoading,setAuthLoading]=useState(true);const[tab,setTab]=useState('dashboard');useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthLoading(false)});const{data:listener}=supabase.auth.onAuthStateChange((_event,session)=>setSession(session));return()=>listener.subscription.unsubscribe()},[]);const role=session?getUserRole(session.user):null;const store=useSupabaseData(role,session?.user);useEffect(()=>{if(role&&!rolePermissions[role].tabs.includes(tab))setTab('dashboard')},[role,tab]);const logout=async()=>{await supabase.auth.signOut()};if(authLoading)return <div className="loadingScreen">Loading AdLift CRM...</div>;if(!session)return <LoginPage/>;if(!role)return <AccessDenied session={session} onLogout={logout}/>;const permissions=rolePermissions[role];const visibleTabs=tabs.filter(([id])=>permissions.tabs.includes(id));const activeTab=permissions.tabs.includes(tab)?tab:'dashboard';const exportData=()=>{const blob=new Blob([JSON.stringify(store.data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='adlift-crm-backup.json';a.click()};const importData=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{const text=String(reader.result||'');if(file.name.toLowerCase().endsWith('.csv')){const rows=parseCsv(text);await store.importRecords({stats:mapCsvRowsToType('stats',rows)});setTab('stats')}else await store.importRecords(JSON.parse(text))}catch{alert('Invalid import file. Use a valid CSV or AdLift JSON backup.')}};reader.readAsText(file);e.target.value=''};return <div className="app"><aside><div className="brand">AdLift<span>CRM</span></div><div className="userBox"><span>{session.user.email}</span><b className="roleBadge">{permissions.label}</b></div>{visibleTabs.map(([id,Icon,label])=><button className={activeTab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={18}/>{label}</button>)}<div className="sideTools">{permissions.canExport&&<button onClick={exportData}><Download size={16}/>Export</button>}{permissions.canImport&&<label><Upload size={16}/>Import<input hidden type="file" accept=".json,.csv,application/json,text/csv" onChange={importData}/></label>}<button onClick={store.loadData}><RefreshCw size={16}/>Refresh</button><button onClick={logout}><LogOut size={16}/>Logout</button></div></aside><main>{store.error&&<div className="dataError">{store.error}</div>}{store.loading?<div className="loadingScreen inline">Loading CRM data...</div>:activeTab==='dashboard'?<Dashboard data={store.data} role={role}/>:activeTab==='activity'?<ActivityLog logs={store.activityLogs}/>:<TableSection type={activeTab} title={tabs.find(t=>t[0]===activeTab)[2]} data={store.data} permissions={permissions} onSave={store.saveRecord} onDelete={store.deleteRecord} onDeleteAll={store.deleteAllRecords}/>}</main></div>}
createRoot(document.getElementById('root')).render(<App/>);
