import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{Plus,Trash2,Edit,Save,X,Search,Download,Upload,Phone,Users,Briefcase,BarChart3,ClipboardList,Home,LogOut,Lock,ShieldCheck,RefreshCw}from'lucide-react';
import{supabase}from'./supabaseClient';
import'./styles.css';

const emptyData={leads:[],clients:[],freelancers:[],submissions:[],stats:[]};
const leadStatuses=['Dialed','Opener','Conversation','Pitched','Interested','Callback','Booked'];
const tabs=[['dashboard',Home,'Dashboard'],['leads',Phone,'Leads'],['clients',Briefcase,'Clients'],['freelancers',Users,'Freelancers'],['submissions',ClipboardList,'Submissions'],['stats',BarChart3,'Cold Call Stats']];
const rolePermissions={admin:{label:'Admin',tabs:['dashboard','leads','clients','freelancers','submissions','stats'],recordTypes:['leads','clients','freelancers','submissions','stats'],canExport:true,canImport:true,canWrite:true,canDelete:true},freelancer:{label:'Freelancer',tabs:['dashboard','submissions','stats'],recordTypes:['submissions','stats'],canExport:false,canImport:false,canWrite:true,canDelete:false}};
const today=()=>new Date().toISOString().slice(0,10);
const isUuid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''));
const norm=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const pick=(row,keys)=>{const k=keys.map(norm).find(x=>row[x]!==undefined);return k?row[k]:''};
function getUserRole(user){const r=String(user?.app_metadata?.role||user?.user_metadata?.role||'').trim().toLowerCase();return rolePermissions[r]?r:null}
function parseCsv(text){const out=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell.trim());if(row.some(Boolean))out.push(row);row=[];cell=''}else cell+=c}row.push(cell.trim());if(row.some(Boolean))out.push(row);if(out.length<2)return[];const headers=out[0].map(norm);return out.slice(1).map(vals=>{const o={};headers.forEach((h,i)=>{if(h)o[h]=vals[i]||''});return o})}
function mapCsvRowsToLeads(rows){return rows.map(r=>({name:pick(r,['name','full name','fullname','lead name','contact name','naam']),phone:pick(r,['phone','phone number','phonenumber','mobile','tel','telephone','gsm','nummer']),email:pick(r,['email','email address','emailaddress','mail','e-mail']),importedDate:today(),status:pick(r,['status','stage'])||'Dialed',notes:pick(r,['notes','note','opmerkingen','notities','description'])}))}
function normalizeLead(x){return{...x,name:x.name||x.fullName||x.contactName||'',phone:x.phone||x.phoneNumber||'',email:x.email||x.emailAddress||'',importedDate:x.importedDate||x.created||today(),status:x.status||'Dialed',notes:x.notes||''}}
function groupRecords(rows){const g={leads:[],clients:[],freelancers:[],submissions:[],stats:[]};(rows||[]).forEach(r=>{if(!g[r.type])return;const p=r.payload||{};g[r.type].push({...r.type==='leads'?normalizeLead(p):p,id:r.id})});return g}
function useSupabaseData(role){const[data,setData]=useState(emptyData),[loading,setLoading]=useState(false),[error,setError]=useState('');const allowed=()=>rolePermissions[role]?.recordTypes||[];const loadData=async()=>{if(!role)return;setLoading(true);setError('');const{data:rows,error}=await supabase.from('crm_records').select('id,type,payload,created_at').in('type',allowed()).order('created_at',{ascending:false});if(error){setError(error.message);setData(emptyData)}else setData(groupRecords(rows));setLoading(false)};useEffect(()=>{loadData()},[role]);const saveRecord=async(type,item)=>{if(!allowed().includes(type))return;setError('');const id=isUuid(item.id)?item.id:crypto.randomUUID();const clean=type==='leads'?normalizeLead(item):item;const payload={...clean,id,created:clean.created||today()};const{error}=await supabase.from('crm_records').upsert({id,type,payload,updated_at:new Date().toISOString()});if(error)return setError(error.message);await loadData()};const deleteRecord=async(_type,id)=>{if(!rolePermissions[role]?.canDelete)return;setError('');const{error}=await supabase.from('crm_records').delete().eq('id',id);if(error)return setError(error.message);await loadData()};const clearType=async(type)=>{if(!rolePermissions[role]?.canDelete)return;setError('');const{error}=await supabase.from('crm_records').delete().eq('type',type);if(error)return setError(error.message);await loadData()};const importRecords=async(obj)=>{if(!rolePermissions[role]?.canImport)return;setError('');const rows=Object.entries(obj||{}).flatMap(([type,items])=>{if(!allowed().includes(type)||!Array.isArray(items))return[];return items.map(item=>{const id=isUuid(item.id)?item.id:crypto.randomUUID();const clean=type==='leads'?normalizeLead(item):item;return{id,type,payload:{...clean,id,created:clean.created||today()},updated_at:new Date().toISOString()}})});if(!rows.length)return;const{error}=await supabase.from('crm_records').upsert(rows);if(error)return setError(error.message);await loadData()};return{data,loading,error,loadData,saveRecord,deleteRecord,clearType,importRecords}}
function Empty({text}){return<div className="empty">{text}</div>}
function AccessDenied({session,onLogout}){return<div className="loginPage"><div className="loginCard"><div className="loginLogo"><ShieldCheck size={24}/><strong>AdLift CRM</strong></div><h1>No role assigned</h1><p>This account is logged in, but it does not have an admin or freelancer role yet.</p><div className="authError">Ask the Supabase admin to set <b>role</b> to <b>admin</b> or <b>freelancer</b> in this user's metadata.</div><small>{session.user.email}</small><button className="primary full" onClick={onLogout}><LogOut size={16}/>Logout</button></div></div>}
function ConfirmModal({onYes,onNo}){return<div className="overlay"><div className="confirmBox"><h2>Delete all leads?</h2><p>Are you sure you want to delete all leads?</p><div className="confirmActions"><button onClick={onNo}>No</button><button className="danger" onClick={onYes}>Yes</button></div></div></div>}
function Modal({title,fields,initial={},onClose,onSave}){const[form,setForm]=useState(initial);const update=(k,v)=>setForm(p=>({...p,[k]:v}));return<div className="overlay"><div className="modal"><div className="modalHead"><h2>{title}</h2><button onClick={onClose}><X size={18}/></button></div><div className="gridForm">{fields.map(f=><label key={f.key}>{f.label}{f.type==='textarea'?<textarea value={form[f.key]||''}onChange={e=>update(f.key,e.target.value)}/>:f.type==='select'?<select value={form[f.key]||f.options?.[0]||''}onChange={e=>update(f.key,e.target.value)}>{(f.options||[]).map(o=><option key={o}value={o}>{o}</option>)}</select>:<input type={f.type||'text'}value={form[f.key]||''}onChange={e=>update(f.key,e.target.value)}/>}</label>)}</div><button className="primary full"onClick={()=>onSave({...form,id:form.id||crypto.randomUUID(),created:form.created||today()})}><Save size={16}/> Save</button></div></div>}
const fieldSets={leads:[{key:'name',label:'Name'},{key:'phone',label:'Phone Number'},{key:'email',label:'Email'},{key:'importedDate',label:'Imported Date',type:'date'},{key:'status',label:'Status',type:'select',options:leadStatuses},{key:'notes',label:'Notes',type:'textarea'}],clients:[{key:'name',label:'Client Name'},{key:'company',label:'Company'},{key:'email',label:'Email'},{key:'plan',label:'Plan'},{key:'status',label:'Status'},{key:'monthly',label:'Monthly Retainer'},{key:'notes',label:'Notes',type:'textarea'}],freelancers:[{key:'name',label:'Name'},{key:'role',label:'Role'},{key:'email',label:'Email'},{key:'pay',label:'Pay Structure'},{key:'status',label:'Status'},{key:'notes',label:'Notes',type:'textarea'}],submissions:[{key:'fullName',label:'Full Name'},{key:'email',label:'Email'},{key:'phone',label:'Phone'},{key:'buyerStatus',label:'Buyer Clients?'},{key:'leadSource',label:'Current Lead Source'},{key:'openToAppointments',label:'Open to Appointments?'},{key:'preferredType',label:'Preferred Client Type'},{key:'notes',label:'Notes',type:'textarea'}],stats:[{key:'date',label:'Date',type:'date'},{key:'dials',label:'Dials',type:'number'},{key:'pickups',label:'Pickups',type:'number'},{key:'conversations',label:'Conversations',type:'number'},{key:'pitches',label:'Pitches',type:'number'},{key:'interested',label:'Interested',type:'number'},{key:'notes',label:'Notes',type:'textarea'}]};
function TableSection({type,title,data,permissions,onSave,onDelete,onClear}){const[search,setSearch]=useState(''),[modal,setModal]=useState(null),[confirm,setConfirm]=useState(false);const rows=data[type]||[],filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())),keys=fieldSets[type].map(f=>f.key);const save=async item=>{await onSave(type,item);setModal(null)};return<section className="card"><div className="sectionTop"><div><h1>{title}</h1><p>{filtered.length} records</p></div><div className="sectionActions">{type==='leads'&&permissions.canDelete&&rows.length>0&&<button className="dangerButton"onClick={()=>setConfirm(true)}><Trash2 size={16}/> Delete All Leads</button>}{permissions.canWrite&&<button className="primary"onClick={()=>setModal(type==='leads'?{importedDate:today(),status:'Dialed'}:{})}><Plus size={16}/> Add</button>}</div></div><div className="search"><Search size={16}/><input placeholder={`Search ${title.toLowerCase()}...`}value={search}onChange={e=>setSearch(e.target.value)}/></div>{filtered.length===0?<Empty text="No records yet. Add one."/>:<div className="tableWrap"><table><thead><tr>{keys.map(k=><th key={k}>{fieldSets[type].find(f=>f.key===k)?.label||k}</th>)}{permissions.canWrite&&<th>Actions</th>}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}>{keys.map(k=><td key={k}>{String(r[k]||'-')}</td>)}{permissions.canWrite&&<td className="actions"><button onClick={()=>setModal(r)}><Edit size={15}/></button>{permissions.canDelete&&<button onClick={()=>onDelete(type,r.id)}><Trash2 size={15}/></button>}</td>}</tr>)}</tbody></table></div>}{modal&&permissions.canWrite&&<Modal title={`${modal.id?'Edit':'Add'} ${title}`}fields={fieldSets[type]}initial={modal}onClose={()=>setModal(null)}onSave={save}/>} {confirm&&<ConfirmModal onNo={()=>setConfirm(false)}onYes={async()=>{await onClear('leads');setConfirm(false)}}/>}</section>}
function Dashboard({data,role}){const totalDials=data.stats.reduce((s,x)=>s+Number(x.dials||0),0),totalPickups=data.stats.reduce((s,x)=>s+Number(x.pickups||0),0),interested=data.stats.reduce((s,x)=>s+Number(x.interested||0),0);const cards=role==='admin'?[['Leads',data.leads.length],['Clients',data.clients.length],['Freelancers',data.freelancers.length],['Dials',totalDials],['Pickups',totalPickups],['Interested',interested]]:[['Submissions',data.submissions.length],['Dials',totalDials],['Pickups',totalPickups],['Interested',interested]];return<section className="card"><h1>AdLift Dashboard</h1><p className="sub">Shared CRM data from Supabase.</p><div className="statsGrid">{cards.map(([a,b])=><div className="stat"key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>{role==='admin'&&<><h2>Pipeline</h2><div className="pipeline">{leadStatuses.map(st=><div className="pipe"key={st}><b>{st}</b><span>{data.leads.filter(l=>(l.status||'').toLowerCase()===st.toLowerCase()).length}</span></div>)}</div></>}</section>}
function LoginPage(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');const login=async e=>{e.preventDefault();setLoading(true);setError('');const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setLoading(false)};return<div className="loginPage"><form className="loginCard"onSubmit={login}><div className="loginLogo"><Lock size={24}/><strong>AdLift CRM</strong></div><h1>Private access</h1><p>Login with the account created in Supabase.</p><label>Email<input type="email"value={email}onChange={e=>setEmail(e.target.value)}placeholder="you@adlift.com"required/></label><label>Password<input type="password"value={password}onChange={e=>setPassword(e.target.value)}placeholder="••••••••"required/></label>{error&&<div className="authError">{error}</div>}<button className="primary full"disabled={loading}>{loading?'Logging in...':'Login'}</button><small>No public sign-up. Create users from Supabase → Authentication → Users.</small></form></div>}
function App(){const[session,setSession]=useState(null),[authLoading,setAuthLoading]=useState(true),[tab,setTab]=useState('dashboard');useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthLoading(false)});const{data:listener}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>listener.subscription.unsubscribe()},[]);const role=session?getUserRole(session.user):null,store=useSupabaseData(role);useEffect(()=>{if(role&&!rolePermissions[role].tabs.includes(tab))setTab('dashboard')},[role,tab]);const logout=async()=>{await supabase.auth.signOut()};if(authLoading)return<div className="loadingScreen">Loading AdLift CRM...</div>;if(!session)return<LoginPage/>;if(!role)return<AccessDenied session={session}onLogout={logout}/>;const permissions=rolePermissions[role],visibleTabs=tabs.filter(([id])=>permissions.tabs.includes(id)),activeTab=permissions.tabs.includes(tab)?tab:'dashboard';const exportData=()=>{const blob=new Blob([JSON.stringify(store.data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='adlift-crm-backup.json';a.click()};const importData=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{const text=String(reader.result||'');if(file.name.toLowerCase().endsWith('.csv')){await store.importRecords({leads:mapCsvRowsToLeads(parseCsv(text))});setTab('leads')}else await store.importRecords(JSON.parse(text))}catch{alert('Invalid import file. Use a valid CSV or AdLift JSON backup.')}};reader.readAsText(file);e.target.value=''};return<div className="app"><aside><div className="brand">AdLift<span>CRM</span></div><div className="userBox"><span>{session.user.email}</span><b className="roleBadge">{permissions.label}</b></div>{visibleTabs.map(([id,Icon,label])=><button className={activeTab===id?'active':''}onClick={()=>setTab(id)}key={id}><Icon size={18}/>{label}</button>)}<div className="sideTools">{permissions.canExport&&<button onClick={exportData}><Download size={16}/>Export</button>}{permissions.canImport&&<label><Upload size={16}/>Import CSV/JSON<input hidden type="file"accept=".json,.csv,application/json,text/csv"onChange={importData}/></label>}<button onClick={store.loadData}><RefreshCw size={16}/>Refresh</button><button onClick={logout}><LogOut size={16}/>Logout</button></div></aside><main>{store.error&&<div className="dataError">{store.error}</div>}{store.loading?<div className="loadingScreen inline">Loading CRM data...</div>:activeTab==='dashboard'?<Dashboard data={store.data}role={role}/>:<TableSection type={activeTab}title={tabs.find(t=>t[0]===activeTab)[2]}data={store.data}permissions={permissions}onSave={store.saveRecord}onDelete={store.deleteRecord}onClear={store.clearType}/>}</main></div>}
createRoot(document.getElementById('root')).render(<App/>);
