-- Phase 7: real-time conversational voice session state.
-- Additive only. Does not originate calls and does not consume campaign queues.
begin;

create table if not exists public.ai_voice_sessions (
  id uuid primary key default gen_random_uuid(),
  attempt_id uuid not null unique references public.ai_call_attempts(id) on delete cascade,
  campaign_id uuid not null references public.ai_call_campaigns(id) on delete restrict,
  prospect_record_id uuid not null references public.crm_records(id) on delete restrict,
  provider_call_id text,
  stream_sid text,
  status text not null default 'reserved' check (status in (
    'reserved','connecting','connected','listening','thinking','speaking','interrupted','ending','completed','failed'
  )),
  stt_provider_slug text,
  llm_provider_slug text,
  tts_provider_slug text,
  turn_no integer not null default 0 check (turn_no >= 0),
  current_turn_id text,
  interim_transcript text,
  last_prospect_utterance text,
  last_agent_response text,
  tts_state text not null default 'idle' check (tts_state in ('idle','buffering','speaking','clearing','cancelled','failed')),
  interruption_count integer not null default 0 check (interruption_count >= 0),
  objection_state jsonb not null default '{}'::jsonb,
  qualification_state jsonb not null default '{}'::jsonb,
  callback_intent jsonb not null default '{}'::jsonb,
  booking_intent jsonb not null default '{}'::jsonb,
  compliance_state jsonb not null default '{}'::jsonb,
  latency_metrics jsonb not null default '{}'::jsonb,
  provider_states jsonb not null default '{}'::jsonb,
  provider_errors jsonb not null default '[]'::jsonb,
  media_token_hash text not null,
  worker_instance text,
  connected_at timestamptz,
  last_activity_at timestamptz not null default now(),
  ended_at timestamptz,
  expires_at timestamptz not null default (now() + interval '45 minutes'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ended_at is null or connected_at is null or ended_at >= connected_at)
);

create index if not exists ai_voice_sessions_status_idx on public.ai_voice_sessions(status,last_activity_at);
create index if not exists ai_voice_sessions_call_idx on public.ai_voice_sessions(provider_call_id) where provider_call_id is not null;
create index if not exists ai_voice_sessions_stream_idx on public.ai_voice_sessions(stream_sid) where stream_sid is not null;

create trigger ai_voice_sessions_set_updated_at
before update on public.ai_voice_sessions
for each row execute function public.ai_set_updated_at();

alter table public.ai_voice_sessions enable row level security;
revoke all on public.ai_voice_sessions from anon,authenticated;
grant select,insert,update,delete on public.ai_voice_sessions to service_role;

-- Final transcript sequence allocation is serialized per attempt so concurrent worker paths
-- cannot write duplicate or out-of-order permanent transcript segments.
create or replace function public.ai_append_transcript_segment(
 p_attempt_id uuid,
 p_speaker text,
 p_start_ms integer,
 p_end_ms integer,
 p_text text,
 p_confidence numeric default null,
 p_provider_slug text default null,
 p_provider_segment_id text default null,
 p_metadata jsonb default '{}'::jsonb
) returns public.ai_transcript_segments
language plpgsql
security definer
set search_path=public
as $$
declare next_seq integer; seg public.ai_transcript_segments;
begin
 if p_speaker not in ('prospect','agent','human','system','unknown') then raise exception 'invalid speaker'; end if;
 if p_start_ms < 0 or (p_end_ms is not null and p_end_ms < p_start_ms) then raise exception 'invalid transcript timestamps'; end if;
 if coalesce(length(trim(p_text)),0)=0 then raise exception 'empty transcript'; end if;
 perform pg_advisory_xact_lock(hashtextextended('transcript:'||p_attempt_id::text,0));
 select coalesce(max(sequence_no),-1)+1 into next_seq from public.ai_transcript_segments where attempt_id=p_attempt_id;
 insert into public.ai_transcript_segments(attempt_id,sequence_no,speaker,start_ms,end_ms,text,is_final,confidence,provider_slug,provider_segment_id,metadata)
 values(p_attempt_id,next_seq,p_speaker,p_start_ms,p_end_ms,trim(p_text),true,p_confidence,p_provider_slug,p_provider_segment_id,coalesce(p_metadata,'{}'::jsonb))
 returning * into seg;
 return seg;
end;$$;

revoke all on function public.ai_append_transcript_segment(uuid,text,integer,integer,text,numeric,text,text,jsonb) from public,anon,authenticated;
grant execute on function public.ai_append_transcript_segment(uuid,text,integer,integer,text,numeric,text,text,jsonb) to service_role;

-- Reserve exactly one media session for an already-created controlled Phase 6 attempt.
-- The token is generated by the server before Twilio origination; only its hash is persisted.
create or replace function public.ai_reserve_voice_session(
 p_attempt_id uuid,
 p_media_token_hash text
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare a public.ai_call_attempts; c public.ai_call_campaigns; existing public.ai_voice_sessions; sid uuid;
begin
 if p_media_token_hash !~ '^[0-9a-f]{64}$' then return jsonb_build_object('reserved',false,'reason','invalid_token_hash'); end if;
 select * into a from public.ai_call_attempts where id=p_attempt_id for update;
 if not found then return jsonb_build_object('reserved',false,'reason','attempt_not_found'); end if;
 if not a.controlled_test then return jsonb_build_object('reserved',false,'reason','not_controlled_test'); end if;
 if a.provider_call_id is not null or a.initiated_at is not null then return jsonb_build_object('reserved',false,'reason','origination_already_started'); end if;
 select * into c from public.ai_call_campaigns where id=a.campaign_id;
 if not found or not c.enabled or c.status<>'active' then return jsonb_build_object('reserved',false,'reason','campaign_not_active'); end if;
 if coalesce(c.stt_provider_slug,'')='' or coalesce(c.llm_provider_slug,'')='' or coalesce(c.tts_provider_slug,'')='' then return jsonb_build_object('reserved',false,'reason','voice_provider_missing'); end if;
 select * into existing from public.ai_voice_sessions where attempt_id=p_attempt_id;
 if found then return jsonb_build_object('reserved',true,'duplicate',true,'session_id',existing.id); end if;
 insert into public.ai_voice_sessions(attempt_id,campaign_id,prospect_record_id,status,stt_provider_slug,llm_provider_slug,tts_provider_slug,media_token_hash)
 values(a.id,a.campaign_id,a.prospect_record_id,'reserved',c.stt_provider_slug,c.llm_provider_slug,c.tts_provider_slug,p_media_token_hash)
 returning id into sid;
 return jsonb_build_object('reserved',true,'duplicate',false,'session_id',sid);
end;$$;

revoke all on function public.ai_reserve_voice_session(uuid,text) from public,anon,authenticated;
grant execute on function public.ai_reserve_voice_session(uuid,text) to service_role;

commit;
